// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.marketplace.search.v1.services;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * This is the base request container for all Finding Service operations.
 * 
 */
public abstract class BaseFindingServiceRequest extends BestMatchFindingServiceRequest implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private SortOrderType sortOrder;
	
    
	/**
     * public getter
     *
     * 
     * Sort the returned items according to a single specified sort order.
     * 
     *
     * @returns com.ebay.marketplace.search.v1.services.SortOrderType
	 */
	public SortOrderType getSortOrder() {
	    return this.sortOrder;
	}
	
	/**
	 * public setter
	 *
     * 
     * Sort the returned items according to a single specified sort order.
     * 
     *
     * @param com.ebay.marketplace.search.v1.services.SortOrderType
	 */
	public void setSortOrder(SortOrderType sortOrder) {
	    this.sortOrder = sortOrder;
	}

}