// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.marketplace.search.v1.services;

import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Container for histogram fields.
 * 
 */
public class ConditionHistogram   {

	@Element
	private Condition condition;
    
	@Element
	private int count;
    
	@Element
	private String delimiter;
    
	private List<Object> any;
    
    
	/**
     * public getter
     *
     * 
     * The ID and name of a condition that was found in the item results.
     * 
     *
     * @returns com.ebay.marketplace.search.v1.services.Condition
	 */
	public Condition getCondition() {
	    return this.condition;
	}
	
	/**
	 * public setter
	 *
     * 
     * The ID and name of a condition that was found in the item results.
     * 
     *
     * @param com.ebay.marketplace.search.v1.services.Condition
	 */
	public void setCondition(Condition condition) {
	    this.condition = condition;
	}
	/**
     * public getter
     *
     * 
     * The number of items found that match the condition.
     * Only counts items where the seller specified the
     * condition by using item.conditionId.
     * 
     *
     * @returns .int
	 */
	public int getCount() {
	    return this.count;
	}
	
	/**
	 * public setter
	 *
     * 
     * The number of items found that match the condition.
     * Only counts items where the seller specified the
     * condition by using item.conditionId.
     * 
     *
     * @param .int
	 */
	public void setCount(int count) {
	    this.count = count;
	}
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getDelimiter() {
	    return this.delimiter;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setDelimiter(String delimiter) {
	    this.delimiter = delimiter;
	}
	/**
	 * public getter
	 *
     * @returns java.util.List<java.lang.Object>
	 */
	public List<Object> getAny() {
	    return this.any;
	}
	
	/**
	 * public setter
	 *
     * @param java.util.List<java.lang.Object>
	 */
	public void setAny(List<Object> any) {
	    this.any = any;
	}

}