// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.marketplace.search.v1.services;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Get request for histogram information on the supplied category or aspect.
 * 
 */
@RootElement(name = "getHistogramsRequest", namespace = "http://www.ebay.com/marketplace/search/v1/services")
public class GetHistogramsRequest extends BaseServiceRequest implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private String categoryId;
	
    
	/**
     * public getter
     *
     * 
     * Specifies the category from which you want to retrieve histogram
     * information.
     * <br><br>
     * If a specified category ID doesn't match an existing category for the
     * site, eBay returns an invalid-category error message. To determine
     * valid categories, use the Shopping API <b
     * class="con">GetCategoryInfo</b> call.
     * <br><br>
     * Retrieving histograms by category is not supported on the eBay Italy
     * site (global ID EBAY-IT) at this time.
     * 
     *
     * @returns java.lang.String
	 */
	public String getCategoryId() {
	    return this.categoryId;
	}
	
	/**
	 * public setter
	 *
     * 
     * Specifies the category from which you want to retrieve histogram
     * information.
     * <br><br>
     * If a specified category ID doesn't match an existing category for the
     * site, eBay returns an invalid-category error message. To determine
     * valid categories, use the Shopping API <b
     * class="con">GetCategoryInfo</b> call.
     * <br><br>
     * Retrieving histograms by category is not supported on the eBay Italy
     * site (global ID EBAY-IT) at this time.
     * 
     *
     * @param java.lang.String
	 */
	public void setCategoryId(String categoryId) {
	    this.categoryId = categoryId;
	}

}