// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.marketplace.search.v1.services;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Contains the returned item listings, if any. The data for each listing is
 * returned in individual item containers.
 * 
 */
public class SearchResult implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private List<SearchItem> item;
	
	@Element
	private String delimiter;
	
	@Attribute  
	private int count;
	
    
	/**
     * public getter
     *
     * 
     * Container for the data of a single item that matches the search criteria.
     * 
     *
     * @returns java.util.List<com.ebay.marketplace.search.v1.services.SearchItem>
	 */
	public List<SearchItem> getItem() {
	    return this.item;
	}
	
	/**
	 * public setter
	 *
     * 
     * Container for the data of a single item that matches the search criteria.
     * 
     *
     * @param java.util.List<com.ebay.marketplace.search.v1.services.SearchItem>
	 */
	public void setItem(List<SearchItem> item) {
	    this.item = item;
	}
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getDelimiter() {
	    return this.delimiter;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setDelimiter(String delimiter) {
	    this.delimiter = delimiter;
	}
	/**
	 * public getter
	 *
     * @returns .int
	 */
	public int getCount() {
	    return this.count;
	}
	
	/**
	 * public setter
	 *
     * @param .int
	 */
	public void setCount(int count) {
	    this.count = count;
	}

}