// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.Date;

/**
 * 
 * Allows a seller to respond to or close an Item Not Received dispute.
 * This can be used to add a comment to an Unpaid Item Dispute
 * only if the request version was lower than 637 when the
 * dispute was created.
 * 
 */
@RootElement(name = "AddDisputeResponseRequest", namespace = "urn:ebay:apis:eBLBaseComponents")
public class AddDisputeResponseRequestType extends AbstractRequestType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "DisputeID")
	private String disputeID;
	
	@Element(name = "MessageText")
	private String messageText;
	
	@Element(name = "DisputeActivity")
	private DisputeActivityCodeType disputeActivity;
	
	@Element(name = "ShippingCarrierUsed")
	private String shippingCarrierUsed;
	
	@Element(name = "ShipmentTrackNumber")
	private String shipmentTrackNumber;
	
	@Element(name = "ShippingTime")
	private Date shippingTime;
	
    
	/**
     * public getter
     *
     * 
     * The unique identifier of the dispute,
     * returned when the dispute was created.
     * 
     *
     * @returns java.lang.String
	 */
	public String getDisputeID() {
	    return this.disputeID;
	}
	
	/**
	 * public setter
	 *
     * 
     * The unique identifier of the dispute,
     * returned when the dispute was created.
     * 
     *
     * @param java.lang.String
	 */
	public void setDisputeID(String disputeID) {
	    this.disputeID = disputeID;
	}
	/**
     * public getter
     *
     * 
     * The text of a comment or response being posted to the dispute. Required
     * when DisputeActivity is SellerAddInformation, SellerComment, or
     * SellerPaymentNotReceived; otherwise, optional.
     * 
     *
     * @returns java.lang.String
	 */
	public String getMessageText() {
	    return this.messageText;
	}
	
	/**
	 * public setter
	 *
     * 
     * The text of a comment or response being posted to the dispute. Required
     * when DisputeActivity is SellerAddInformation, SellerComment, or
     * SellerPaymentNotReceived; otherwise, optional.
     * 
     *
     * @param java.lang.String
	 */
	public void setMessageText(String messageText) {
	    this.messageText = messageText;
	}
	/**
     * public getter
     *
     * 
     * The type of activity the seller is taking on the dispute. The allowed value is
     * determined by the current value of DisputeState, returned by GetDispute or
     * GetUserDisputes. Some values relate to Unpaid Item disputes and other values relate
     * to buyer-created disputes known as Item Not Received or Significantly Not As
     * Described disputes.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.DisputeActivityCodeType
	 */
	public DisputeActivityCodeType getDisputeActivity() {
	    return this.disputeActivity;
	}
	
	/**
	 * public setter
	 *
     * 
     * The type of activity the seller is taking on the dispute. The allowed value is
     * determined by the current value of DisputeState, returned by GetDispute or
     * GetUserDisputes. Some values relate to Unpaid Item disputes and other values relate
     * to buyer-created disputes known as Item Not Received or Significantly Not As
     * Described disputes.
     * 
     *
     * @param ebay.apis.eblbasecomponents.DisputeActivityCodeType
	 */
	public void setDisputeActivity(DisputeActivityCodeType disputeActivity) {
	    this.disputeActivity = disputeActivity;
	}
	/**
     * public getter
     *
     * 
     * The shipping carrier used to ship the item in dispute. Non-alphanumeric
     * characters are not allowed. This field (along with ShipmentTrackNumber) is
     * required if DisputeActivity is SellerShippedItem.
     * 
     *
     * @returns java.lang.String
	 */
	public String getShippingCarrierUsed() {
	    return this.shippingCarrierUsed;
	}
	
	/**
	 * public setter
	 *
     * 
     * The shipping carrier used to ship the item in dispute. Non-alphanumeric
     * characters are not allowed. This field (along with ShipmentTrackNumber) is
     * required if DisputeActivity is SellerShippedItem.
     * 
     *
     * @param java.lang.String
	 */
	public void setShippingCarrierUsed(String shippingCarrierUsed) {
	    this.shippingCarrierUsed = shippingCarrierUsed;
	}
	/**
     * public getter
     *
     * 
     * The tracking number associated with one package of a shipment. The seller is
     * responsible for the accuracy of the shipment tracking number, as eBay only
     * verifies that the tracking number is consistent with the numbering scheme
     * used by the specified shipping carrier, but cannot verify the accuracy of
     * the tracking number. This field (along with ShippingCarrierUsed) is required
     * if DisputeActivity is SellerShippedItem.
     * 
     *
     * @returns java.lang.String
	 */
	public String getShipmentTrackNumber() {
	    return this.shipmentTrackNumber;
	}
	
	/**
	 * public setter
	 *
     * 
     * The tracking number associated with one package of a shipment. The seller is
     * responsible for the accuracy of the shipment tracking number, as eBay only
     * verifies that the tracking number is consistent with the numbering scheme
     * used by the specified shipping carrier, but cannot verify the accuracy of
     * the tracking number. This field (along with ShippingCarrierUsed) is required
     * if DisputeActivity is SellerShippedItem.
     * 
     *
     * @param java.lang.String
	 */
	public void setShipmentTrackNumber(String shipmentTrackNumber) {
	    this.shipmentTrackNumber = shipmentTrackNumber;
	}
	/**
     * public getter
     *
     * 
     * This timestamp indicates the date and time when the item under dispute was
     * shipped. This field is required if DisputeActivity is SellerShippedItem.
     * 
     *
     * @returns java.util.Date
	 */
	public Date getShippingTime() {
	    return this.shippingTime;
	}
	
	/**
	 * public setter
	 *
     * 
     * This timestamp indicates the date and time when the item under dispute was
     * shipped. This field is required if DisputeActivity is SellerShippedItem.
     * 
     *
     * @param java.util.Date
	 */
	public void setShippingTime(Date shippingTime) {
	    this.shippingTime = shippingTime;
	}

}