// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Type defining the response of the <b>AddDispute</b> call. Upon a successful 
 * call, the response contains a newly created DisputeID value, which confirms that the 
 * the Unpaid Item or Mutually Canceled Transaction case was successfully created.
 * 
 */
@RootElement(name = "AddDisputeResponse", namespace = "urn:ebay:apis:eBLBaseComponents")
public class AddDisputeResponseType extends AbstractResponseType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "DisputeID")
	private String disputeID;
	
    
	/**
     * public getter
     *
     * 
     * The unique identifier of the Unpaid Item or Mutually Canceled Transaction case 
     * that was successfully created with the <b>AddDispute</b> call.
     * 
     *
     * @returns java.lang.String
	 */
	public String getDisputeID() {
	    return this.disputeID;
	}
	
	/**
	 * public setter
	 *
     * 
     * The unique identifier of the Unpaid Item or Mutually Canceled Transaction case 
     * that was successfully created with the <b>AddDispute</b> call.
     * 
     *
     * @param java.lang.String
	 */
	public void setDisputeID(String disputeID) {
	    this.disputeID = disputeID;
	}

}