// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Appends a horizontal rule, then a message about what time the
 * addition was made by the seller, and then the seller-specified text.
 * 
 */
@RootElement(name = "AddToItemDescriptionRequest", namespace = "urn:ebay:apis:eBLBaseComponents")
public class AddToItemDescriptionRequestType extends AbstractRequestType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "ItemID")
	private String itemID;
	
	@Element(name = "Description")
	private String description;
	
    
	/**
     * public getter
     *
     * 
     * Unique item ID that identifies the target item listing, the description
     * of which is appended with the text specified in Description.
     * 
     *
     * @returns java.lang.String
	 */
	public String getItemID() {
	    return this.itemID;
	}
	
	/**
	 * public setter
	 *
     * 
     * Unique item ID that identifies the target item listing, the description
     * of which is appended with the text specified in Description.
     * 
     *
     * @param java.lang.String
	 */
	public void setItemID(String itemID) {
	    this.itemID = itemID;
	}
	/**
     * public getter
     *
     * 
     * Specifies the text to append to the end of the listing's description.
     * Text appended to a listing's description must abide by the rules
     * applicable to this data (such as no JavaScript) as is the case when
     * first listing the item.
     * 
     *
     * @returns java.lang.String
	 */
	public String getDescription() {
	    return this.description;
	}
	
	/**
	 * public setter
	 *
     * 
     * Specifies the text to append to the end of the listing's description.
     * Text appended to a listing's description must abide by the rules
     * applicable to this data (such as no JavaScript) as is the case when
     * first listing the item.
     * 
     *
     * @param java.lang.String
	 */
	public void setDescription(String description) {
	    this.description = description;
	}

}