// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * This type is deprecated as the Bid Assistant feature is no longer available.
 *  
 * 
 */
public class BidGroupItemType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "Item")
	private ItemType item;
	
	@Element(name = "BidGroupItemStatus")
	private BidGroupItemStatusCodeType bidGroupItemStatus;
	
	@Element(name = "MaxBidAmount")
	private AmountType maxBidAmount;
	
    
	/**
     * public getter
     *
     * 
     * 
     * Contains a list of the items in a bid group.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.ItemType
	 */
	public ItemType getItem() {
	    return this.item;
	}
	
	/**
	 * public setter
	 *
     * 
     * 
     * Contains a list of the items in a bid group.
     * 
     *
     * @param ebay.apis.eblbasecomponents.ItemType
	 */
	public void setItem(ItemType item) {
	    this.item = item;
	}
	/**
     * public getter
     *
     * 
     * 
     * Contains the status of the items in the bid group.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.BidGroupItemStatusCodeType
	 */
	public BidGroupItemStatusCodeType getBidGroupItemStatus() {
	    return this.bidGroupItemStatus;
	}
	
	/**
	 * public setter
	 *
     * 
     * 
     * Contains the status of the items in the bid group.
     * 
     *
     * @param ebay.apis.eblbasecomponents.BidGroupItemStatusCodeType
	 */
	public void setBidGroupItemStatus(BidGroupItemStatusCodeType bidGroupItemStatus) {
	    this.bidGroupItemStatus = bidGroupItemStatus;
	}
	/**
     * public getter
     *
     * 
     * 
     * Contains the maximum bid amount for the item in the bid group.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.AmountType
	 */
	public AmountType getMaxBidAmount() {
	    return this.maxBidAmount;
	}
	
	/**
	 * public setter
	 *
     * 
     * 
     * Contains the maximum bid amount for the item in the bid group.
     * 
     *
     * @param ebay.apis.eblbasecomponents.AmountType
	 */
	public void setMaxBidAmount(AmountType maxBidAmount) {
	    this.maxBidAmount = maxBidAmount;
	}

}