// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Contains information about a user as a buyer.
 * 
 */
public class BuyerType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "ShippingAddress")
	private AddressType shippingAddress;
	
    
	/**
     * public getter
     *
     * 
     * Contains the shipping address of the buyer. See AddressType for its child elements. GetAllBidders
     * is returning only Country and PostalCode currently.
     * Output only.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.AddressType
	 */
	public AddressType getShippingAddress() {
	    return this.shippingAddress;
	}
	
	/**
	 * public setter
	 *
     * 
     * Contains the shipping address of the buyer. See AddressType for its child elements. GetAllBidders
     * is returning only Country and PostalCode currently.
     * Output only.
     * 
     *
     * @param ebay.apis.eblbasecomponents.AddressType
	 */
	public void setShippingAddress(AddressType shippingAddress) {
	    this.shippingAddress = shippingAddress;
	}

}