// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 *  Indicates whether shipping options are available for the category.
 * 
 */
public class ClassifiedAdShippingMethodEnabledDefinitionType implements Serializable {

    private static final long serialVersionUID = -1L;

    

}