// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Fields in this type provide IDs and values for item conditions 
 * (in GetCategoryFeatures).
 * 
 */
public class ConditionType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "ID")
	private Integer id;
	
	@Element(name = "DisplayName")
	private String displayName;
	
    
	/**
     * public getter
     *
     * 
     * The numeric ID of a condition (e.g., 1000). Use the ID in 
     * AddItem and related calls.
     * 
     *
     * @returns java.lang.Integer
	 */
	public Integer getId() {
	    return this.id;
	}
	
	/**
	 * public setter
	 *
     * 
     * The numeric ID of a condition (e.g., 1000). Use the ID in 
     * AddItem and related calls.
     * 
     *
     * @param java.lang.Integer
	 */
	public void setId(Integer id) {
	    this.id = id;
	}
	/**
     * public getter
     *
     * 
     * The human-readable label for the condition (e.g., "New"). 
     * This value is typically localized for each site. 
     * The display name can vary by category. 
     * For example, condition ID 1000 could be called
     * "New: with Tags" in one category and "Brand New" in another.
     * 
     *
     * @returns java.lang.String
	 */
	public String getDisplayName() {
	    return this.displayName;
	}
	
	/**
	 * public setter
	 *
     * 
     * The human-readable label for the condition (e.g., "New"). 
     * This value is typically localized for each site. 
     * The display name can vary by category. 
     * For example, condition ID 1000 could be called
     * "New: with Tags" in one category and "Brand New" in another.
     * 
     *
     * @param java.lang.String
	 */
	public void setDisplayName(String displayName) {
	    this.displayName = displayName;
	}

}