// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Confirms the identity of the user by returning the UserID and the EIASToken belonging to
 * the user.
 * 
 */
@RootElement(name = "ConfirmIdentityResponse", namespace = "urn:ebay:apis:eBLBaseComponents")
public class ConfirmIdentityResponseType extends AbstractResponseType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "UserID")
	private String userID;
	
    
	/**
     * public getter
     *
     * 
     * Unique eBay user ID for the user.
     * 
     *
     * @returns java.lang.String
	 */
	public String getUserID() {
	    return this.userID;
	}
	
	/**
	 * public setter
	 *
     * 
     * Unique eBay user ID for the user.
     * 
     *
     * @param java.lang.String
	 */
	public void setUserID(String userID) {
	    this.userID = userID;
	}

}