// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Returns the ID of a user who has gone through an application's consent flow
 * process for obtaining an authorization token.
 * 
 */
@RootElement(name = "ConfirmIdentityRequest", namespace = "urn:ebay:apis:eBLBaseComponents")
public class ConfirmIdentityRequestType extends AbstractRequestType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "SessionID")
	private String sessionID;
	
    
	/**
     * public getter
     *
     * 
     * A string obtained by making a GetSessionID call, passed in redirect
     * URL to the eBay signin page.
     * 
     *
     * @returns java.lang.String
	 */
	public String getSessionID() {
	    return this.sessionID;
	}
	
	/**
	 * public setter
	 *
     * 
     * A string obtained by making a GetSessionID call, passed in redirect
     * URL to the eBay signin page.
     * 
     *
     * @param java.lang.String
	 */
	public void setSessionID(String sessionID) {
	    this.sessionID = sessionID;
	}

}