// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * This type is deprecated as the <b>GetProduct*</b> calls are no longer available.
 * 
 * 
 */
public class DataElementSetType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "DataElement")
	private String dataElement;
	
	@Element(name = "DataElementID")
	private Integer dataElementID;
	
	@Attribute  
	private Integer attributeSetID;
	
    
	/**
     * public getter
     *
     * 
     * 
     * An HTML snippet that specifies hints for the user, help links, help graphics,
     * and other supplemental information that varies per characteristic set.
     * In GetProductSearchPage, one DataElement value contains a hint (including an empty HTML achor element),
     * one DataElement value may contain a URL to insert into the HTML anchor as the href value,
     * and one DataElement value may contain a URL that eBay uses as a help graphic.
     * If no value is available in the meta-data, a dash ("--") is returned instead.
     * Usage of this information is optional and may require developers to inspect
     * the information to determine how it can be applied in an application.
     * Because this is returned as a string, the HTML markup elements are escaped with
     * character entity references (e.g.,&lt;a href=""&gt;&lt;Attributes&gt;...).
     * See the appendices in the eBay Web Services guide for general information about
     * string data types.
     * 
     *
     * @returns java.lang.String
	 */
	public String getDataElement() {
	    return this.dataElement;
	}
	
	/**
	 * public setter
	 *
     * 
     * 
     * An HTML snippet that specifies hints for the user, help links, help graphics,
     * and other supplemental information that varies per characteristic set.
     * In GetProductSearchPage, one DataElement value contains a hint (including an empty HTML achor element),
     * one DataElement value may contain a URL to insert into the HTML anchor as the href value,
     * and one DataElement value may contain a URL that eBay uses as a help graphic.
     * If no value is available in the meta-data, a dash ("--") is returned instead.
     * Usage of this information is optional and may require developers to inspect
     * the information to determine how it can be applied in an application.
     * Because this is returned as a string, the HTML markup elements are escaped with
     * character entity references (e.g.,&lt;a href=""&gt;&lt;Attributes&gt;...).
     * See the appendices in the eBay Web Services guide for general information about
     * string data types.
     * 
     *
     * @param java.lang.String
	 */
	public void setDataElement(String dataElement) {
	    this.dataElement = dataElement;
	}
	/**
     * public getter
     *
     * 
     * 
     * Identifier for a data element. This is primarily for internal use by eBay.
     * Developers can choose to inspect this information and determine how it
     * can be applied in their applications.
     * 
     *
     * @returns java.lang.Integer
	 */
	public Integer getDataElementID() {
	    return this.dataElementID;
	}
	
	/**
	 * public setter
	 *
     * 
     * 
     * Identifier for a data element. This is primarily for internal use by eBay.
     * Developers can choose to inspect this information and determine how it
     * can be applied in their applications.
     * 
     *
     * @param java.lang.Integer
	 */
	public void setDataElementID(Integer dataElementID) {
	    this.dataElementID = dataElementID;
	}
	/**
	 * public getter
	 *
     * @returns java.lang.Integer
	 */
	public Integer getAttributeSetID() {
	    return this.attributeSetID;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.Integer
	 */
	public void setAttributeSetID(Integer attributeSetID) {
	    this.attributeSetID = attributeSetID;
	}

}