// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Deletes a Selling Manager product.
 * This call is subject to change without notice; the
 * deprecation process is inapplicable to this call.
 * 
 */
@RootElement(name = "DeleteSellingManagerProductRequest", namespace = "urn:ebay:apis:eBLBaseComponents")
public class DeleteSellingManagerProductRequestType extends AbstractRequestType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "ProductID")
	private Long productID;
	
    
	/**
     * public getter
     *
     * 
     * ID of the product to be deleted.
     * 
     *
     * @returns java.lang.Long
	 */
	public Long getProductID() {
	    return this.productID;
	}
	
	/**
	 * public setter
	 *
     * 
     * ID of the product to be deleted.
     * 
     *
     * @param java.lang.Long
	 */
	public void setProductID(Long productID) {
	    this.productID = productID;
	}

}