// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Represents a list of disputes. Can hold zero or more Dispute
 * types, each of which describes a dispute.
 * 
 */
public class DisputeArrayType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "Dispute")
	private List<DisputeType> dispute;
	
    
	/**
     * public getter
     *
     * 
     * The information that describes a dispute, including
     * the buyer's name, the transaction ID, the dispute state
     * and status, whether the dispute is resolved,
     * and any messages posted to the dispute.
     * 
     *
     * @returns java.util.List<ebay.apis.eblbasecomponents.DisputeType>
	 */
	public List<DisputeType> getDispute() {
	    return this.dispute;
	}
	
	/**
	 * public setter
	 *
     * 
     * The information that describes a dispute, including
     * the buyer's name, the transaction ID, the dispute state
     * and status, whether the dispute is resolved,
     * and any messages posted to the dispute.
     * 
     *
     * @param java.util.List<ebay.apis.eblbasecomponents.DisputeType>
	 */
	public void setDispute(List<DisputeType> dispute) {
	    this.dispute = dispute;
	}

}