// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 *  
 * Contains one or more stored comments for use as feedback to buyers.
 * 
 */
public class FeedbackCommentArrayType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "StoredCommentText")
	private List<String> storedCommentText;
	
    
	/**
     * public getter
     *
     * 
     * This comment is for use as feedback for buyers. No more than ten (10) 
     * comments can be stored. 
     * 
     *
     * @returns java.util.List<java.lang.String>
	 */
	public List<String> getStoredCommentText() {
	    return this.storedCommentText;
	}
	
	/**
	 * public setter
	 *
     * 
     * This comment is for use as feedback for buyers. No more than ten (10) 
     * comments can be stored. 
     * 
     *
     * @param java.util.List<java.lang.String>
	 */
	public void setStoredCommentText(List<String> storedCommentText) {
	    this.storedCommentText = storedCommentText;
	}

}