// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Contains the data for one type of feedback for one predefined time
 * period. Parent FeedbackPeriodArrayType object indicates the type of
 * feedback counted: positive, neutral, negative, or total. Output only,
 * in the summary feedback data returned by GetFeedback.
 * 
 */
public class FeedbackPeriodType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "PeriodInDays")
	private Integer periodInDays;
	
	@Element(name = "Count")
	private Integer count;
	
    
	/**
     * public getter
     *
     * 
     * Indicates the time period for the feedback count. Returns a value indicating
     * the number of days prior to the call for which feedback entries of the particular
     * type are counted. Returned if no detail level is specified.
     * 
     *
     * @returns java.lang.Integer
	 */
	public Integer getPeriodInDays() {
	    return this.periodInDays;
	}
	
	/**
	 * public setter
	 *
     * 
     * Indicates the time period for the feedback count. Returns a value indicating
     * the number of days prior to the call for which feedback entries of the particular
     * type are counted. Returned if no detail level is specified.
     * 
     *
     * @param java.lang.Integer
	 */
	public void setPeriodInDays(Integer periodInDays) {
	    this.periodInDays = periodInDays;
	}
	/**
     * public getter
     *
     * 
     * Count of the feedback entries received by the user for the time period prior to the
     * call indicated in PeriodInDays. Returned if no detail level is specified.
     * 
     *
     * @returns java.lang.Integer
	 */
	public Integer getCount() {
	    return this.count;
	}
	
	/**
	 * public setter
	 *
     * 
     * Count of the feedback entries received by the user for the time period prior to the
     * call indicated in PeriodInDays. Returned if no detail level is specified.
     * 
     *
     * @param java.lang.Integer
	 */
	public void setCount(Integer count) {
	    this.count = count;
	}

}