// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Returns number of leads and contact and other information for each lead. One
 * AdFormatLead node is returned for each lead.
 * 
 */
@RootElement(name = "GetAdFormatLeadsResponse", namespace = "urn:ebay:apis:eBLBaseComponents")
public class GetAdFormatLeadsResponseType extends AbstractResponseType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "AdFormatLead")
	private List<AdFormatLeadType> adFormatLead;
	
	@Element(name = "AdFormatLeadCount")
	private Integer adFormatLeadCount;
	
    
	/**
     * public getter
     *
     * 
     * Contains contact and other information for one lead. One node is
     * returned for each lead. Only returned at a detail level of ReturnAll. At
     * least one lead must be available for the specified item to return
     * AdFormatLead.
     * 
     *
     * @returns java.util.List<ebay.apis.eblbasecomponents.AdFormatLeadType>
	 */
	public List<AdFormatLeadType> getAdFormatLead() {
	    return this.adFormatLead;
	}
	
	/**
	 * public setter
	 *
     * 
     * Contains contact and other information for one lead. One node is
     * returned for each lead. Only returned at a detail level of ReturnAll. At
     * least one lead must be available for the specified item to return
     * AdFormatLead.
     * 
     *
     * @param java.util.List<ebay.apis.eblbasecomponents.AdFormatLeadType>
	 */
	public void setAdFormatLead(List<AdFormatLeadType> adFormatLead) {
	    this.adFormatLead = adFormatLead;
	}
	/**
     * public getter
     *
     * 
     * The total number of leads returned. Only returned if you do not
     * specify a detail level.
     * 
     *
     * @returns java.lang.Integer
	 */
	public Integer getAdFormatLeadCount() {
	    return this.adFormatLeadCount;
	}
	
	/**
	 * public setter
	 *
     * 
     * The total number of leads returned. Only returned if you do not
     * specify a detail level.
     * 
     *
     * @param java.lang.Integer
	 */
	public void setAdFormatLeadCount(Integer adFormatLeadCount) {
	    this.adFormatLeadCount = adFormatLeadCount;
	}

}