// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.Date;

/**
 * 
 * Returns contact information to a seller for both bidders
 * and users who have made offers (via Best Offer) during
 * an active listing.
 * 
 */
@RootElement(name = "GetUserContactDetailsResponse", namespace = "urn:ebay:apis:eBLBaseComponents")
public class GetUserContactDetailsResponseType extends AbstractResponseType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "UserID")
	private String userID;
	
	@Element(name = "ContactAddress")
	private AddressType contactAddress;
	
	@Element(name = "RegistrationDate")
	private Date registrationDate;
	
    
	/**
     * public getter
     *
     * 
     * An eBay ID that uniquely identifies a given
     * user. The eBay username of the requested
     * contact.
     * 
     *
     * @returns java.lang.String
	 */
	public String getUserID() {
	    return this.userID;
	}
	
	/**
	 * public setter
	 *
     * 
     * An eBay ID that uniquely identifies a given
     * user. The eBay username of the requested
     * contact.
     * 
     *
     * @param java.lang.String
	 */
	public void setUserID(String userID) {
	    this.userID = userID;
	}
	/**
     * public getter
     *
     * 
     * Contact information for the requested contact.
     * Note that the email address is NOT returned.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.AddressType
	 */
	public AddressType getContactAddress() {
	    return this.contactAddress;
	}
	
	/**
	 * public setter
	 *
     * 
     * Contact information for the requested contact.
     * Note that the email address is NOT returned.
     * 
     *
     * @param ebay.apis.eblbasecomponents.AddressType
	 */
	public void setContactAddress(AddressType contactAddress) {
	    this.contactAddress = contactAddress;
	}
	/**
     * public getter
     *
     * 
     * The date and time that the requested contact
     * registered with eBay.
     * 
     *
     * @returns java.util.Date
	 */
	public Date getRegistrationDate() {
	    return this.registrationDate;
	}
	
	/**
	 * public setter
	 *
     * 
     * The date and time that the requested contact
     * registered with eBay.
     * 
     *
     * @param java.util.Date
	 */
	public void setRegistrationDate(Date registrationDate) {
	    this.registrationDate = registrationDate;
	}

}