// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 *          This type provides information about one order line item in a Global Shipping package. The package can contain multiple units of a given order line item.
 * 
 */
public class LineItemType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "Quantity")
	private Integer quantity;
	
	@Element(name = "CountryOfOrigin")
	private String countryOfOrigin;
	
	@Element(name = "Description")
	private String description;
	
	@Element(name = "ItemID")
	private String itemID;
	
	@Element(name = "TransactionID")
	private String transactionID;
	
    
	/**
     * public getter
     *
     * 
     * The number of units of the order line item in this package; this is required for customs. The seller must ensure that this matches the quantity of the order line item enclosed in the package.
     * <br/><br/>
     * This value must be a positive integer, and it can't be greater than the quantity of this item specified in the original transaction.
     * 
     *
     * @returns java.lang.Integer
	 */
	public Integer getQuantity() {
	    return this.quantity;
	}
	
	/**
	 * public setter
	 *
     * 
     * The number of units of the order line item in this package; this is required for customs. The seller must ensure that this matches the quantity of the order line item enclosed in the package.
     * <br/><br/>
     * This value must be a positive integer, and it can't be greater than the quantity of this item specified in the original transaction.
     * 
     *
     * @param java.lang.Integer
	 */
	public void setQuantity(Integer quantity) {
	    this.quantity = quantity;
	}
	/**
     * public getter
     *
     * 
     * The Country of Manufacture for the order line item; this is required for customs. This should identify the country in which more than 50% of the value of the item was created.
     * <br/><br/>
     * This value must conform to the ISO 3166 two-letter country code standard. 
     * To see the list of currently supported codes, and the English names associated with each code 
     * (e.g., KY="Cayman Islands"), call <b>GeteBayDetails</b> 
     * with <b>DetailName</b> set to <b>CountryDetails</b>.
     * 
     *
     * @returns java.lang.String
	 */
	public String getCountryOfOrigin() {
	    return this.countryOfOrigin;
	}
	
	/**
	 * public setter
	 *
     * 
     * The Country of Manufacture for the order line item; this is required for customs. This should identify the country in which more than 50% of the value of the item was created.
     * <br/><br/>
     * This value must conform to the ISO 3166 two-letter country code standard. 
     * To see the list of currently supported codes, and the English names associated with each code 
     * (e.g., KY="Cayman Islands"), call <b>GeteBayDetails</b> 
     * with <b>DetailName</b> set to <b>CountryDetails</b>.
     * 
     *
     * @param java.lang.String
	 */
	public void setCountryOfOrigin(String countryOfOrigin) {
	    this.countryOfOrigin = countryOfOrigin;
	}
	/**
     * public getter
     *
     * 
     *  The item description of the order line item, based on its <strong>ItemID</strong>.
     * 
     *
     * @returns java.lang.String
	 */
	public String getDescription() {
	    return this.description;
	}
	
	/**
	 * public setter
	 *
     * 
     *  The item description of the order line item, based on its <strong>ItemID</strong>.
     * 
     *
     * @param java.lang.String
	 */
	public void setDescription(String description) {
	    this.description = description;
	}
	/**
     * public getter
     *
     * 
     * Unique identifier for the eBay item listing of the order line item. A listing can have multiple order line items (transactions), but only one <b>ItemID</b>. Unless an <b>OrderLineItemID</b> or <b>SKU</b> value is specified in the same node, this field is required for each <b>ItemTransactionID</b> node included in the request.
     * 
     *
     * @returns java.lang.String
	 */
	public String getItemID() {
	    return this.itemID;
	}
	
	/**
	 * public setter
	 *
     * 
     * Unique identifier for the eBay item listing of the order line item. A listing can have multiple order line items (transactions), but only one <b>ItemID</b>. Unless an <b>OrderLineItemID</b> or <b>SKU</b> value is specified in the same node, this field is required for each <b>ItemTransactionID</b> node included in the request.
     * 
     *
     * @param java.lang.String
	 */
	public void setItemID(String itemID) {
	    this.itemID = itemID;
	}
	/**
     * public getter
     *
     * 
     * Unique identifier for an eBay order line item (transaction). The <b>TransactionID</b> should match the <b>ItemID</b> specified in each <b>ItemTransactionID</b> node included in the request. Optionally, an <b>OrderLineItemID</b> value can substitute for the <b>ItemID</b>/<b>TransactionID</b> pair.
     * 
     *
     * @returns java.lang.String
	 */
	public String getTransactionID() {
	    return this.transactionID;
	}
	
	/**
	 * public setter
	 *
     * 
     * Unique identifier for an eBay order line item (transaction). The <b>TransactionID</b> should match the <b>ItemID</b> specified in each <b>ItemTransactionID</b> node included in the request. Optionally, an <b>OrderLineItemID</b> value can substitute for the <b>ItemID</b>/<b>TransactionID</b> pair.
     * 
     *
     * @param java.lang.String
	 */
	public void setTransactionID(String transactionID) {
	    this.transactionID = transactionID;
	}

}