// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Contains the message portion of a listing tip that is returned by the Listing Analyzer engine.
 * 
 */
public class ListingTipMessageType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "ListingTipMessageID")
	private String listingTipMessageID;
	
	@Element(name = "ShortMessage")
	private String shortMessage;
	
	@Element(name = "LongMessage")
	private String longMessage;
	
	@Element(name = "HelpURLPath")
	private String helpURLPath;
	
    
	/**
     * public getter
     *
     * 
     * Identifier for the tip message. Primarily for internal use. This value may change over time.
     * 
     *
     * @returns java.lang.String
	 */
	public String getListingTipMessageID() {
	    return this.listingTipMessageID;
	}
	
	/**
	 * public setter
	 *
     * 
     * Identifier for the tip message. Primarily for internal use. This value may change over time.
     * 
     *
     * @param java.lang.String
	 */
	public void setListingTipMessageID(String listingTipMessageID) {
	    this.listingTipMessageID = listingTipMessageID;
	}
	/**
     * public getter
     *
     * 
     * Brief version of the tip message.
     * 
     *
     * @returns java.lang.String
	 */
	public String getShortMessage() {
	    return this.shortMessage;
	}
	
	/**
	 * public setter
	 *
     * 
     * Brief version of the tip message.
     * 
     *
     * @param java.lang.String
	 */
	public void setShortMessage(String shortMessage) {
	    this.shortMessage = shortMessage;
	}
	/**
     * public getter
     *
     * 
     * Detailed version of the tip message.
     * 
     *
     * @returns java.lang.String
	 */
	public String getLongMessage() {
	    return this.longMessage;
	}
	
	/**
	 * public setter
	 *
     * 
     * Detailed version of the tip message.
     * 
     *
     * @param java.lang.String
	 */
	public void setLongMessage(String longMessage) {
	    this.longMessage = longMessage;
	}
	/**
     * public getter
     *
     * 
     * Path part of a URL for a "Learn More" link that points to a relevant eBay Web site online help page.
     * The path is relative to http://pages.ebay.XX, where XX is the 2-letter site code
     * (e.g., http://pages.ebay.de for the eBay Germany site). Applications should append the
     * URL to the appropriate path for the user's site.
     * 
     *
     * @returns java.lang.String
	 */
	public String getHelpURLPath() {
	    return this.helpURLPath;
	}
	
	/**
	 * public setter
	 *
     * 
     * Path part of a URL for a "Learn More" link that points to a relevant eBay Web site online help page.
     * The path is relative to http://pages.ebay.XX, where XX is the 2-letter site code
     * (e.g., http://pages.ebay.de for the eBay Germany site). Applications should append the
     * URL to the appropriate path for the user's site.
     * 
     *
     * @param java.lang.String
	 */
	public void setHelpURLPath(String helpURLPath) {
	    this.helpURLPath = helpURLPath;
	}

}