// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Defines details about recommended names and values for custom Item Specifics.
 * 
 */
public class NameRecommendationType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "Name")
	private String name;
	
	@Element(name = "ValidationRules")
	private RecommendationValidationRulesType validationRules;
	
	@Element(name = "ValueRecommendation")
	private List<ValueRecommendationType> valueRecommendation;
	
	@Element(name = "HelpURL")
	private String helpURL;
	
	@Element(name = "Source")
	private ItemSpecificSourceCodeType source;
	
	@Element(name = "HelpText")
	private String helpText;
	
    
	/**
     * public getter
     *
     * 
     * A recommended Item Specific name.
     * Always returned when NameRecommendation is returned.
     * 
     *
     * @returns java.lang.String
	 */
	public String getName() {
	    return this.name;
	}
	
	/**
	 * public setter
	 *
     * 
     * A recommended Item Specific name.
     * Always returned when NameRecommendation is returned.
     * 
     *
     * @param java.lang.String
	 */
	public void setName(String name) {
	    this.name = name;
	}
	/**
     * public getter
     *
     * 
     * Constraints that eBay places on this Item Specific.
     * Always returned when NameRecommendation is returned.
     * As a general rule, AddItem and related calls will not be blocked
     * if you don't use eBay's recommendations, except where specified
     * in this documentation.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.RecommendationValidationRulesType
	 */
	public RecommendationValidationRulesType getValidationRules() {
	    return this.validationRules;
	}
	
	/**
	 * public setter
	 *
     * 
     * Constraints that eBay places on this Item Specific.
     * Always returned when NameRecommendation is returned.
     * As a general rule, AddItem and related calls will not be blocked
     * if you don't use eBay's recommendations, except where specified
     * in this documentation.
     * 
     *
     * @param ebay.apis.eblbasecomponents.RecommendationValidationRulesType
	 */
	public void setValidationRules(RecommendationValidationRulesType validationRules) {
	    this.validationRules = validationRules;
	}
	/**
     * public getter
     *
     * 
     * A recommended value (if any) for the Item Specific name.
     * Only returned when a recommended value is available in the system.<br>
     * <br>
     * If an Item Specific has value dependencies (i.e., if it has value recommendations that contain Relationship), then
     * all of its value recommendations are returned.
     * If it has no dependencies, then the maximum number of 
     * value recommendations that can be returned is limited by the number 
     * you specified in MaxValuesPerName.
     * 
     *
     * @returns java.util.List<ebay.apis.eblbasecomponents.ValueRecommendationType>
	 */
	public List<ValueRecommendationType> getValueRecommendation() {
	    return this.valueRecommendation;
	}
	
	/**
	 * public setter
	 *
     * 
     * A recommended value (if any) for the Item Specific name.
     * Only returned when a recommended value is available in the system.<br>
     * <br>
     * If an Item Specific has value dependencies (i.e., if it has value recommendations that contain Relationship), then
     * all of its value recommendations are returned.
     * If it has no dependencies, then the maximum number of 
     * value recommendations that can be returned is limited by the number 
     * you specified in MaxValuesPerName.
     * 
     *
     * @param java.util.List<ebay.apis.eblbasecomponents.ValueRecommendationType>
	 */
	public void setValueRecommendation(List<ValueRecommendationType> valueRecommendation) {
	    this.valueRecommendation = valueRecommendation;
	}
	/**
     * public getter
     *
     * 
     * A page on the eBay Web site with context-specific help tips that
     * provide useful information about this Item Specific.
     * Only returned when an applicable page is available in the system.
     * 
     *
     * @returns java.lang.String
	 */
	public String getHelpURL() {
	    return this.helpURL;
	}
	
	/**
	 * public setter
	 *
     * 
     * A page on the eBay Web site with context-specific help tips that
     * provide useful information about this Item Specific.
     * Only returned when an applicable page is available in the system.
     * 
     *
     * @param java.lang.String
	 */
	public void setHelpURL(String helpURL) {
	    this.helpURL = helpURL;
	}
	/**
     * public getter
     *
     * 
     * Reserved for future use.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.ItemSpecificSourceCodeType
	 */
	public ItemSpecificSourceCodeType getSource() {
	    return this.source;
	}
	
	/**
	 * public setter
	 *
     * 
     * Reserved for future use.
     * 
     *
     * @param ebay.apis.eblbasecomponents.ItemSpecificSourceCodeType
	 */
	public void setSource(ItemSpecificSourceCodeType source) {
	    this.source = source;
	}
	/**
     * public getter
     *
     * 
     * Help-text defines the purpose of the tag.
     * The help text will be shown only when it is available for the particular tag
     * 
     *
     * @returns java.lang.String
	 */
	public String getHelpText() {
	    return this.helpText;
	}
	
	/**
	 * public setter
	 *
     * 
     * Help-text defines the purpose of the tag.
     * The help text will be shown only when it is available for the particular tag
     * 
     *
     * @param java.lang.String
	 */
	public void setHelpText(String helpText) {
	    this.helpText = helpText;
	}

}