// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * This type is deprecated as Pictures Manager was retired.
 * 
 * 
 */
public class PictureManagerSubscriptionType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "SubscriptionLevel")
	private PictureManagerSubscriptionLevelCodeType subscriptionLevel;
	
	@Element(name = "Fee")
	private AmountType fee;
	
	@Element(name = "StorageSize")
	private Integer storageSize;
	
    
	/**
     * public getter
     *
     * 
     * 
     * The level of Picture Manager subscription. Each level has a
     * monthly fee and provides a certain amount of storage space.
     *     
     *
     * @returns ebay.apis.eblbasecomponents.PictureManagerSubscriptionLevelCodeType
	 */
	public PictureManagerSubscriptionLevelCodeType getSubscriptionLevel() {
	    return this.subscriptionLevel;
	}
	
	/**
	 * public setter
	 *
     * 
     * 
     * The level of Picture Manager subscription. Each level has a
     * monthly fee and provides a certain amount of storage space.
     *     
     *
     * @param ebay.apis.eblbasecomponents.PictureManagerSubscriptionLevelCodeType
	 */
	public void setSubscriptionLevel(PictureManagerSubscriptionLevelCodeType subscriptionLevel) {
	    this.subscriptionLevel = subscriptionLevel;
	}
	/**
     * public getter
     *
     * 
     * 
     *       The monthly fee for the subscription. Read-only value.
     *     
     *
     * @returns ebay.apis.eblbasecomponents.AmountType
	 */
	public AmountType getFee() {
	    return this.fee;
	}
	
	/**
	 * public setter
	 *
     * 
     * 
     *       The monthly fee for the subscription. Read-only value.
     *     
     *
     * @param ebay.apis.eblbasecomponents.AmountType
	 */
	public void setFee(AmountType fee) {
	    this.fee = fee;
	}
	/**
     * public getter
     *
     * 
     * 
     *       The total amount of storage space available for the subscription type.
     *       Read-only value.
     *     
     *
     * @returns java.lang.Integer
	 */
	public Integer getStorageSize() {
	    return this.storageSize;
	}
	
	/**
	 * public setter
	 *
     * 
     * 
     *       The total amount of storage space available for the subscription type.
     *       Read-only value.
     *     
     *
     * @param java.lang.Integer
	 */
	public void setStorageSize(Integer storageSize) {
	    this.storageSize = storageSize;
	}

}