// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.Date;

/**
 * 
 * Details for a single promotional sale.
 * 
 */
public class PromotionalSaleType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "PromotionalSaleID")
	private Long promotionalSaleID;
	
	@Element(name = "PromotionalSaleName")
	private String promotionalSaleName;
	
	@Element(name = "PromotionalSaleItemIDArray")
	private ItemIDArrayType promotionalSaleItemIDArray;
	
	@Element(name = "Status")
	private PromotionalSaleStatusCodeType status;
	
	@Element(name = "DiscountType")
	private DiscountCodeType discountType;
	
	@Element(name = "DiscountValue")
	private Double discountValue;
	
	@Element(name = "PromotionalSaleStartTime")
	private Date promotionalSaleStartTime;
	
	@Element(name = "PromotionalSaleEndTime")
	private Date promotionalSaleEndTime;
	
	@Element(name = "PromotionalSaleType")
	private PromotionalSaleTypeCodeType promotionalSaleType;
	
    
	/**
     * public getter
     *
     * 
     * Unique ID of a promotional sale (discount and/or free shipping) for items.
     * This field is an input field only for the SetPromotionalSale call
     * and only if you are not adding a new promotional sale.
     * 
     *
     * @returns java.lang.Long
	 */
	public Long getPromotionalSaleID() {
	    return this.promotionalSaleID;
	}
	
	/**
	 * public setter
	 *
     * 
     * Unique ID of a promotional sale (discount and/or free shipping) for items.
     * This field is an input field only for the SetPromotionalSale call
     * and only if you are not adding a new promotional sale.
     * 
     *
     * @param java.lang.Long
	 */
	public void setPromotionalSaleID(Long promotionalSaleID) {
	    this.promotionalSaleID = promotionalSaleID;
	}
	/**
     * public getter
     *
     * 
     * Name of a promotional sale for items.
     * 
     *
     * @returns java.lang.String
	 */
	public String getPromotionalSaleName() {
	    return this.promotionalSaleName;
	}
	
	/**
	 * public setter
	 *
     * 
     * Name of a promotional sale for items.
     * 
     *
     * @param java.lang.String
	 */
	public void setPromotionalSaleName(String promotionalSaleName) {
	    this.promotionalSaleName = promotionalSaleName;
	}
	/**
     * public getter
     *
     * 
     * Items covered by a promotional sale.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.ItemIDArrayType
	 */
	public ItemIDArrayType getPromotionalSaleItemIDArray() {
	    return this.promotionalSaleItemIDArray;
	}
	
	/**
	 * public setter
	 *
     * 
     * Items covered by a promotional sale.
     * 
     *
     * @param ebay.apis.eblbasecomponents.ItemIDArrayType
	 */
	public void setPromotionalSaleItemIDArray(ItemIDArrayType promotionalSaleItemIDArray) {
	    this.promotionalSaleItemIDArray = promotionalSaleItemIDArray;
	}
	/**
     * public getter
     *
     * 
     * Status of a promotional sale for items.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.PromotionalSaleStatusCodeType
	 */
	public PromotionalSaleStatusCodeType getStatus() {
	    return this.status;
	}
	
	/**
	 * public setter
	 *
     * 
     * Status of a promotional sale for items.
     * 
     *
     * @param ebay.apis.eblbasecomponents.PromotionalSaleStatusCodeType
	 */
	public void setStatus(PromotionalSaleStatusCodeType status) {
	    this.status = status;
	}
	/**
     * public getter
     *
     * 
     * Type of a promotional sale discount for items (for example, percentage). 
     * Applies to price discount sales only.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.DiscountCodeType
	 */
	public DiscountCodeType getDiscountType() {
	    return this.discountType;
	}
	
	/**
	 * public setter
	 *
     * 
     * Type of a promotional sale discount for items (for example, percentage). 
     * Applies to price discount sales only.
     * 
     *
     * @param ebay.apis.eblbasecomponents.DiscountCodeType
	 */
	public void setDiscountType(DiscountCodeType discountType) {
	    this.discountType = discountType;
	}
	/**
     * public getter
     *
     * 
     * Value of a promotional sale discount for items, a percentage discount 
     * or a fixed amount reduction. Percentage discounts must be at least 5% and 
     * cannot exceed 75% of the original listing price. Fixed amount discounts 
     * will be in the currency of the original listing. 
     * Applies to price discount sales only.
     * 
     *
     * @returns java.lang.Double
	 */
	public Double getDiscountValue() {
	    return this.discountValue;
	}
	
	/**
	 * public setter
	 *
     * 
     * Value of a promotional sale discount for items, a percentage discount 
     * or a fixed amount reduction. Percentage discounts must be at least 5% and 
     * cannot exceed 75% of the original listing price. Fixed amount discounts 
     * will be in the currency of the original listing. 
     * Applies to price discount sales only.
     * 
     *
     * @param java.lang.Double
	 */
	public void setDiscountValue(Double discountValue) {
	    this.discountValue = discountValue;
	}
	/**
     * public getter
     *
     * 
     * Start date of a promotional sale for items. Promotional sales can start
     * immediately or be scheduled to start at a later date. Some sites require
     * items to have been listed for a specific duration before they can be added
     * to a promotional sale (for example, on the US site, items must have been 
     * listed for a day before they can be added to a promotional sale).
     * 
     *
     * @returns java.util.Date
	 */
	public Date getPromotionalSaleStartTime() {
	    return this.promotionalSaleStartTime;
	}
	
	/**
	 * public setter
	 *
     * 
     * Start date of a promotional sale for items. Promotional sales can start
     * immediately or be scheduled to start at a later date. Some sites require
     * items to have been listed for a specific duration before they can be added
     * to a promotional sale (for example, on the US site, items must have been 
     * listed for a day before they can be added to a promotional sale).
     * 
     *
     * @param java.util.Date
	 */
	public void setPromotionalSaleStartTime(Date promotionalSaleStartTime) {
	    this.promotionalSaleStartTime = promotionalSaleStartTime;
	}
	/**
     * public getter
     *
     * 
     * End date of a promotional sale discount for items. Maximum listing durations
     * vary by site from 14 days to 45 days. The minimum promotional sale duration is 1 day for most sites, but 3 days on some sites.
     * 
     *
     * @returns java.util.Date
	 */
	public Date getPromotionalSaleEndTime() {
	    return this.promotionalSaleEndTime;
	}
	
	/**
	 * public setter
	 *
     * 
     * End date of a promotional sale discount for items. Maximum listing durations
     * vary by site from 14 days to 45 days. The minimum promotional sale duration is 1 day for most sites, but 3 days on some sites.
     * 
     *
     * @param java.util.Date
	 */
	public void setPromotionalSaleEndTime(Date promotionalSaleEndTime) {
	    this.promotionalSaleEndTime = promotionalSaleEndTime;
	}
	/**
     * public getter
     *
     * 
     * Type of promotional sale: price discount, free shipping, or both.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.PromotionalSaleTypeCodeType
	 */
	public PromotionalSaleTypeCodeType getPromotionalSaleType() {
	    return this.promotionalSaleType;
	}
	
	/**
	 * public setter
	 *
     * 
     * Type of promotional sale: price discount, free shipping, or both.
     * 
     *
     * @param ebay.apis.eblbasecomponents.PromotionalSaleTypeCodeType
	 */
	public void setPromotionalSaleType(PromotionalSaleTypeCodeType promotionalSaleType) {
	    this.promotionalSaleType = promotionalSaleType;
	}

}