// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Contains information about the funding source for the refund.
 * 
 */
public class RefundFundingSourceType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "RefundingSourceType")
	private RefundingSourceTypeCodeType refundingSourceType;
	
	@Element(name = "AccountNumber")
	private String accountNumber;
	
	@Element(name = "RefundAmount")
	private AmountType refundAmount;
	
	@Element(name = "SellerExternalTransactionID")
	private String sellerExternalTransactionID;
	
	@Element(name = "BuyerExternalTransactionID")
	private String buyerExternalTransactionID;
	
    
	/**
     * public getter
     *
     * 
     * The source from which the refund was made. RefundFundingSource elements are returned 
     * (for GetOrders and other order retrieval calls) for DE/AT orders subject to the 
     * new eBay payment process.<br/><br/>
     * <span class="tablenote">
     * <strong>Note:</strong> The introduction of the new eBay payment process for the entire German and
     * Austrian eBay marketplace has been delayed until 2013. 
     * </span>
     * 
     *
     * @returns ebay.apis.eblbasecomponents.RefundingSourceTypeCodeType
	 */
	public RefundingSourceTypeCodeType getRefundingSourceType() {
	    return this.refundingSourceType;
	}
	
	/**
	 * public setter
	 *
     * 
     * The source from which the refund was made. RefundFundingSource elements are returned 
     * (for GetOrders and other order retrieval calls) for DE/AT orders subject to the 
     * new eBay payment process.<br/><br/>
     * <span class="tablenote">
     * <strong>Note:</strong> The introduction of the new eBay payment process for the entire German and
     * Austrian eBay marketplace has been delayed until 2013. 
     * </span>
     * 
     *
     * @param ebay.apis.eblbasecomponents.RefundingSourceTypeCodeType
	 */
	public void setRefundingSourceType(RefundingSourceTypeCodeType refundingSourceType) {
	    this.refundingSourceType = refundingSourceType;
	}
	/**
     * public getter
     *
     * 
     * The account number of the funding source. RefundFundingSource elements are returned 
     * (for GetOrders and other order retrieval calls) for DE/AT orders subject to the 
     * new eBay payment process.<br/><br/>
     * <span class="tablenote">
     * <strong>Note:</strong> The introduction of the new eBay payment process for the entire German and
     * Austrian eBay marketplace has been delayed until 2013. 
     * </span>
     * 
     *
     * @returns java.lang.String
	 */
	public String getAccountNumber() {
	    return this.accountNumber;
	}
	
	/**
	 * public setter
	 *
     * 
     * The account number of the funding source. RefundFundingSource elements are returned 
     * (for GetOrders and other order retrieval calls) for DE/AT orders subject to the 
     * new eBay payment process.<br/><br/>
     * <span class="tablenote">
     * <strong>Note:</strong> The introduction of the new eBay payment process for the entire German and
     * Austrian eBay marketplace has been delayed until 2013. 
     * </span>
     * 
     *
     * @param java.lang.String
	 */
	public void setAccountNumber(String accountNumber) {
	    this.accountNumber = accountNumber;
	}
	/**
     * public getter
     *
     * 
     * The amount of the refund. RefundFundingSource elements are returned 
     * (for GetOrders and other order retrieval calls) for DE/AT orders subject to the 
     * new eBay payment process.<br/><br/>
     * <span class="tablenote">
     * <strong>Note:</strong> The introduction of the new eBay payment process for the entire German and
     * Austrian eBay marketplace has been delayed until 2013. 
     * </span>
     * 
     *
     * @returns ebay.apis.eblbasecomponents.AmountType
	 */
	public AmountType getRefundAmount() {
	    return this.refundAmount;
	}
	
	/**
	 * public setter
	 *
     * 
     * The amount of the refund. RefundFundingSource elements are returned 
     * (for GetOrders and other order retrieval calls) for DE/AT orders subject to the 
     * new eBay payment process.<br/><br/>
     * <span class="tablenote">
     * <strong>Note:</strong> The introduction of the new eBay payment process for the entire German and
     * Austrian eBay marketplace has been delayed until 2013. 
     * </span>
     * 
     *
     * @param ebay.apis.eblbasecomponents.AmountType
	 */
	public void setRefundAmount(AmountType refundAmount) {
	    this.refundAmount = refundAmount;
	}
	/**
     * public getter
     *
     * 
     * The external transaction ID of the seller's account. RefundFundingSource elements are returned 
     * (for GetOrders and other order retrieval calls) for DE/AT orders subject to the 
     * new eBay payment process.<br/><br/>
     * <span class="tablenote">
     * <strong>Note:</strong> The introduction of the new eBay payment process for the entire German and
     * Austrian eBay marketplace has been delayed until 2013.  
     * </span>
     * 
     *
     * @returns java.lang.String
	 */
	public String getSellerExternalTransactionID() {
	    return this.sellerExternalTransactionID;
	}
	
	/**
	 * public setter
	 *
     * 
     * The external transaction ID of the seller's account. RefundFundingSource elements are returned 
     * (for GetOrders and other order retrieval calls) for DE/AT orders subject to the 
     * new eBay payment process.<br/><br/>
     * <span class="tablenote">
     * <strong>Note:</strong> The introduction of the new eBay payment process for the entire German and
     * Austrian eBay marketplace has been delayed until 2013.  
     * </span>
     * 
     *
     * @param java.lang.String
	 */
	public void setSellerExternalTransactionID(String sellerExternalTransactionID) {
	    this.sellerExternalTransactionID = sellerExternalTransactionID;
	}
	/**
     * public getter
     *
     * 
     * The external transaction ID of the buyer's account. RefundFundingSource elements are returned 
     * (for GetOrders and other order retrieval calls) for DE/AT orders subject to the 
     * new eBay payment process.<br/><br/>
     * <span class="tablenote">
     * <strong>Note:</strong> The introduction of the new eBay payment process for the entire German and
     * Austrian eBay marketplace has been delayed until 2013. 
     * </span>
     * 
     *
     * @returns java.lang.String
	 */
	public String getBuyerExternalTransactionID() {
	    return this.buyerExternalTransactionID;
	}
	
	/**
	 * public setter
	 *
     * 
     * The external transaction ID of the buyer's account. RefundFundingSource elements are returned 
     * (for GetOrders and other order retrieval calls) for DE/AT orders subject to the 
     * new eBay payment process.<br/><br/>
     * <span class="tablenote">
     * <strong>Note:</strong> The introduction of the new eBay payment process for the entire German and
     * Austrian eBay marketplace has been delayed until 2013. 
     * </span>
     * 
     *
     * @param java.lang.String
	 */
	public void setBuyerExternalTransactionID(String buyerExternalTransactionID) {
	    this.buyerExternalTransactionID = buyerExternalTransactionID;
	}

}