// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Contains an array of refunds.
 * 
 */
public class RefundArrayType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "Refund")
	private List<RefundType> refund;
	
    
	/**
     * public getter
     *
     * 
     * Contains information about one refund. Applicable to Half.com (for GetOrders). Applicable to refunds issued with eBay's new Payment Process.<br/><br/>
     *     <span class="tablenote"><strong>Note:</strong> Refund containers are returned for eBay's new Payment Process in the Sandbox environment beginning in April 2012, and in the Production environment beginning in May 2012.</span>
     * 
     *
     * @returns java.util.List<ebay.apis.eblbasecomponents.RefundType>
	 */
	public List<RefundType> getRefund() {
	    return this.refund;
	}
	
	/**
	 * public setter
	 *
     * 
     * Contains information about one refund. Applicable to Half.com (for GetOrders). Applicable to refunds issued with eBay's new Payment Process.<br/><br/>
     *     <span class="tablenote"><strong>Note:</strong> Refund containers are returned for eBay's new Payment Process in the Sandbox environment beginning in April 2012, and in the Production environment beginning in May 2012.</span>
     * 
     *
     * @param java.util.List<ebay.apis.eblbasecomponents.RefundType>
	 */
	public void setRefund(List<RefundType> refund) {
	    this.refund = refund;
	}

}