// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Provides information about the visibility level you've earned for your eBay listings. 
 * When you have a better search standing, your listings may receive higher 
 * placement in Best Match search results.
 * 
 */
public class SearchStandingDashboardType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "Status")
	private SearchStandingStatusCodeType status;
	
    
	/**
     * public getter
     *
     * 
     * Your earned search standing status. To qualify for a Standard or Raised
     * search standing, make sure your ratings meet or exceed the required minimum
     * levels in buyer satisfaction (see BuyerSatisfaction.Status in this call) and
     * detailed seller ratings (DSRs). See GetFeedback for details.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.SearchStandingStatusCodeType
	 */
	public SearchStandingStatusCodeType getStatus() {
	    return this.status;
	}
	
	/**
	 * public setter
	 *
     * 
     * Your earned search standing status. To qualify for a Standard or Raised
     * search standing, make sure your ratings meet or exceed the required minimum
     * levels in buyer satisfaction (see BuyerSatisfaction.Status in this call) and
     * detailed seller ratings (DSRs). See GetFeedback for details.
     * 
     *
     * @param ebay.apis.eblbasecomponents.SearchStandingStatusCodeType
	 */
	public void setStatus(SearchStandingStatusCodeType status) {
	    this.status = status;
	}

}