// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 *       Creates or updates a custom page on a user's eBay Store.
 *     
 */
@RootElement(name = "SetStoreCustomPageRequest", namespace = "urn:ebay:apis:eBLBaseComponents")
public class SetStoreCustomPageRequestType extends AbstractRequestType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "CustomPage")
	private StoreCustomPageType customPage;
	
    
	/**
     * public getter
     *
     * 
     *      The custom page being submitted.
     *   
     *
     * @returns ebay.apis.eblbasecomponents.StoreCustomPageType
	 */
	public StoreCustomPageType getCustomPage() {
	    return this.customPage;
	}
	
	/**
	 * public setter
	 *
     * 
     *      The custom page being submitted.
     *   
     *
     * @param ebay.apis.eblbasecomponents.StoreCustomPageType
	 */
	public void setCustomPage(StoreCustomPageType customPage) {
	    this.customPage = customPage;
	}

}