// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 *   Set of Store custom pages.
 *   
 */
public class StoreCustomPageArrayType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "CustomPage")
	private List<StoreCustomPageType> customPage;
	
    
	/**
     * public getter
     *
     * 
     *   A Store custom page.
     *   
     *
     * @returns java.util.List<ebay.apis.eblbasecomponents.StoreCustomPageType>
	 */
	public List<StoreCustomPageType> getCustomPage() {
	    return this.customPage;
	}
	
	/**
	 * public setter
	 *
     * 
     *   A Store custom page.
     *   
     *
     * @param java.util.List<ebay.apis.eblbasecomponents.StoreCustomPageType>
	 */
	public void setCustomPage(List<StoreCustomPageType> customPage) {
	    this.customPage = customPage;
	}

}