// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 *   Store font set.
 *   
 */
public class StoreFontType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "NameFace")
	private StoreFontFaceCodeType nameFace;
	
	@Element(name = "NameSize")
	private StoreFontSizeCodeType nameSize;
	
	@Element(name = "NameColor")
	private String nameColor;
	
	@Element(name = "TitleFace")
	private StoreFontFaceCodeType titleFace;
	
	@Element(name = "TitleSize")
	private StoreFontSizeCodeType titleSize;
	
	@Element(name = "TitleColor")
	private String titleColor;
	
	@Element(name = "DescFace")
	private StoreFontFaceCodeType descFace;
	
	@Element(name = "DescSize")
	private StoreFontSizeCodeType descSize;
	
	@Element(name = "DescColor")
	private String descColor;
	
    
	/**
     * public getter
     *
     * 
     * Font for the Store name.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.StoreFontFaceCodeType
	 */
	public StoreFontFaceCodeType getNameFace() {
	    return this.nameFace;
	}
	
	/**
	 * public setter
	 *
     * 
     * Font for the Store name.
     * 
     *
     * @param ebay.apis.eblbasecomponents.StoreFontFaceCodeType
	 */
	public void setNameFace(StoreFontFaceCodeType nameFace) {
	    this.nameFace = nameFace;
	}
	/**
     * public getter
     *
     * 
     * Font size for the Store name.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.StoreFontSizeCodeType
	 */
	public StoreFontSizeCodeType getNameSize() {
	    return this.nameSize;
	}
	
	/**
	 * public setter
	 *
     * 
     * Font size for the Store name.
     * 
     *
     * @param ebay.apis.eblbasecomponents.StoreFontSizeCodeType
	 */
	public void setNameSize(StoreFontSizeCodeType nameSize) {
	    this.nameSize = nameSize;
	}
	/**
     * public getter
     *
     * 
     * Font color for the Store name. Specified in 6-digit Hex format.
     * For example: F6F6C9
     * 
     *
     * @returns java.lang.String
	 */
	public String getNameColor() {
	    return this.nameColor;
	}
	
	/**
	 * public setter
	 *
     * 
     * Font color for the Store name. Specified in 6-digit Hex format.
     * For example: F6F6C9
     * 
     *
     * @param java.lang.String
	 */
	public void setNameColor(String nameColor) {
	    this.nameColor = nameColor;
	}
	/**
     * public getter
     *
     * 
     * Font for the Store section title.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.StoreFontFaceCodeType
	 */
	public StoreFontFaceCodeType getTitleFace() {
	    return this.titleFace;
	}
	
	/**
	 * public setter
	 *
     * 
     * Font for the Store section title.
     * 
     *
     * @param ebay.apis.eblbasecomponents.StoreFontFaceCodeType
	 */
	public void setTitleFace(StoreFontFaceCodeType titleFace) {
	    this.titleFace = titleFace;
	}
	/**
     * public getter
     *
     * 
     * Font size for the Store section title.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.StoreFontSizeCodeType
	 */
	public StoreFontSizeCodeType getTitleSize() {
	    return this.titleSize;
	}
	
	/**
	 * public setter
	 *
     * 
     * Font size for the Store section title.
     * 
     *
     * @param ebay.apis.eblbasecomponents.StoreFontSizeCodeType
	 */
	public void setTitleSize(StoreFontSizeCodeType titleSize) {
	    this.titleSize = titleSize;
	}
	/**
     * public getter
     *
     * 
     * Font color for the Store section title. Specified in 6-digit Hex
     * format. For example: F6F6C9
     * 
     *
     * @returns java.lang.String
	 */
	public String getTitleColor() {
	    return this.titleColor;
	}
	
	/**
	 * public setter
	 *
     * 
     * Font color for the Store section title. Specified in 6-digit Hex
     * format. For example: F6F6C9
     * 
     *
     * @param java.lang.String
	 */
	public void setTitleColor(String titleColor) {
	    this.titleColor = titleColor;
	}
	/**
     * public getter
     *
     * 
     * Font for the Store description.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.StoreFontFaceCodeType
	 */
	public StoreFontFaceCodeType getDescFace() {
	    return this.descFace;
	}
	
	/**
	 * public setter
	 *
     * 
     * Font for the Store description.
     * 
     *
     * @param ebay.apis.eblbasecomponents.StoreFontFaceCodeType
	 */
	public void setDescFace(StoreFontFaceCodeType descFace) {
	    this.descFace = descFace;
	}
	/**
     * public getter
     *
     * 
     * Font size for the Store description.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.StoreFontSizeCodeType
	 */
	public StoreFontSizeCodeType getDescSize() {
	    return this.descSize;
	}
	
	/**
	 * public setter
	 *
     * 
     * Font size for the Store description.
     * 
     *
     * @param ebay.apis.eblbasecomponents.StoreFontSizeCodeType
	 */
	public void setDescSize(StoreFontSizeCodeType descSize) {
	    this.descSize = descSize;
	}
	/**
     * public getter
     *
     * 
     * Font color for the Store description. Specified in 6-digit Hex
     * format. For example: F6F6C9
     * 
     *
     * @returns java.lang.String
	 */
	public String getDescColor() {
	    return this.descColor;
	}
	
	/**
	 * public setter
	 *
     * 
     * Font color for the Store description. Specified in 6-digit Hex
     * format. For example: F6F6C9
     * 
     *
     * @param java.lang.String
	 */
	public void setDescColor(String descColor) {
	    this.descColor = descColor;
	}

}