// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * A generic type used for histograms.
 * 
 */
public class DomainHistogramType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "Domain")
	private List<HistogramEntryType> domain;
	
    
	/**
     * public getter
     *
     * 
     * Each histogram entry shows how many matching products
     * were found in each matching domain. A domain is like a high-level
     * category, or a group of categories whose items share the same basic
     * product characteristics.
     * 
     *
     * @returns java.util.List<ebay.apis.eblbasecomponents.HistogramEntryType>
	 */
	public List<HistogramEntryType> getDomain() {
	    return this.domain;
	}
	
	/**
	 * public setter
	 *
     * 
     * Each histogram entry shows how many matching products
     * were found in each matching domain. A domain is like a high-level
     * category, or a group of categories whose items share the same basic
     * product characteristics.
     * 
     *
     * @param java.util.List<ebay.apis.eblbasecomponents.HistogramEntryType>
	 */
	public void setDomain(List<HistogramEntryType> domain) {
	    this.domain = domain;
	}

}