// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Searches Half.com for stock product information (stock description
 * and Item Specifics), such as information about a particular
 * kind of DVD or book. Also, retrieves up to 30 Half.com listings associated
 * with a product.
 * 
 */
@RootElement(name = "FindHalfProductsRequest", namespace = "urn:ebay:apis:eBLBaseComponents")
public class FindHalfProductsRequestType extends AbstractRequestType  {

	@Element(name = "IncludeSelector")
	private String includeSelector;
    
	@Element(name = "AvailableItemsOnly")
	private Boolean availableItemsOnly;
    
	@Element(name = "DomainName")
	private List<String> domainName;
    
	@Element(name = "ProductID")
	private ProductIDType productID;
    
	@Element(name = "QueryKeywords")
	private String queryKeywords;
    
	@Element(name = "SellerID")
	private String sellerID;
    
	@Element(name = "ProductSort")
	private ProductSortCodeType productSort;
    
	@Element(name = "SortOrder")
	private SortOrderCodeType sortOrder;
    
	@Element(name = "MaxEntries")
	private Integer maxEntries;
    
	@Element(name = "PageNumber")
	private Integer pageNumber;
    
    
	/**
     * public getter
     *
     * 
     * Defines standard subsets of fields to return within the
     * response.<br>
     * <br>
     * If you don't specify this field, the call returns a default
     * set of fields, focusing on product details only
     * (see the "Detail Controls" link below). If you specify this
     * field, the additional fields you retrieve can affect the call's
     * response time (performance).<br>
     * <br>
     * <b>Applicable values</b>:
     * <p class="ename">&bull;&nbsp;&nbsp; Items</p>
     * <p class="edef">Include a brief set of item fields
     * in the response.
     * Only applicable when you are searching by ProductID.
     * Not applicable with QueryKeywords.</p>
     * <p class="ename">&bull;&nbsp;&nbsp; DomainHistogram</p>
     * <p class="edef">Include the DomainHistogram in
     * the response. The histogram lists the number of matching
     * products found and the domains in which they were found.
     * (A domain is like a high-level category.)
     * When many matching products are found, you may see
     * significantly slower response times when you include
     * the histogram.</p>
     * <br>
     * <br>
     * Use a comma to specify multiple values. (In this case,
     * the results are cumulative.) See "FindHalfProducts Samples"
     * for an example of how to use this field.<br>
     * <br>
     * See "Detail Controls" for a complete list of
     * fields that can be returned for each selector.
     * 
     *
     * @returns java.lang.String
	 */
	public String getIncludeSelector() {
	    return this.includeSelector;
	}
	
	/**
	 * public setter
	 *
     * 
     * Defines standard subsets of fields to return within the
     * response.<br>
     * <br>
     * If you don't specify this field, the call returns a default
     * set of fields, focusing on product details only
     * (see the "Detail Controls" link below). If you specify this
     * field, the additional fields you retrieve can affect the call's
     * response time (performance).<br>
     * <br>
     * <b>Applicable values</b>:
     * <p class="ename">&bull;&nbsp;&nbsp; Items</p>
     * <p class="edef">Include a brief set of item fields
     * in the response.
     * Only applicable when you are searching by ProductID.
     * Not applicable with QueryKeywords.</p>
     * <p class="ename">&bull;&nbsp;&nbsp; DomainHistogram</p>
     * <p class="edef">Include the DomainHistogram in
     * the response. The histogram lists the number of matching
     * products found and the domains in which they were found.
     * (A domain is like a high-level category.)
     * When many matching products are found, you may see
     * significantly slower response times when you include
     * the histogram.</p>
     * <br>
     * <br>
     * Use a comma to specify multiple values. (In this case,
     * the results are cumulative.) See "FindHalfProducts Samples"
     * for an example of how to use this field.<br>
     * <br>
     * See "Detail Controls" for a complete list of
     * fields that can be returned for each selector.
     * 
     *
     * @param java.lang.String
	 */
	public void setIncludeSelector(String includeSelector) {
	    this.includeSelector = includeSelector;
	}
	/**
     * public getter
     *
     * 
     * If true, only retrieve data for products that have been used to
     * pre-fill active listings on the Half.com site.
     * If false, retrieve all products that match the query.
     * This is useful when you use QueryKeywords and you only want to
     * find products that have associated items (that is, where ItemArray
     * would not be empty).<br>
     * <br>
     * By default, AvailableItemsOnly does not retrieve an ItemArray; it only controls
     * which products are returned (or counted). When you use QueryKeywords in your
     * request, only products are returned, ItemArray is never returned.
     * To retrieve an ItemArray, use a ProductID in your request instead of a
     * QueryKeyword and specify Items in the IncludeSelector field.
     * 
     *
     * @returns java.lang.Boolean
	 */
	public Boolean getAvailableItemsOnly() {
	    return this.availableItemsOnly;
	}
	
	/**
	 * public setter
	 *
     * 
     * If true, only retrieve data for products that have been used to
     * pre-fill active listings on the Half.com site.
     * If false, retrieve all products that match the query.
     * This is useful when you use QueryKeywords and you only want to
     * find products that have associated items (that is, where ItemArray
     * would not be empty).<br>
     * <br>
     * By default, AvailableItemsOnly does not retrieve an ItemArray; it only controls
     * which products are returned (or counted). When you use QueryKeywords in your
     * request, only products are returned, ItemArray is never returned.
     * To retrieve an ItemArray, use a ProductID in your request instead of a
     * QueryKeyword and specify Items in the IncludeSelector field.
     * 
     *
     * @param java.lang.Boolean
	 */
	public void setAvailableItemsOnly(Boolean availableItemsOnly) {
	    this.availableItemsOnly = availableItemsOnly;
	}
	/**
     * public getter
     *
     * 
     * A domain to search in. This is like searching a section of
     * a catalog. If not specified, the product search is conducted
     * across all domains.
     * DomainName is an unbounded field. If you are using a URL, and you want
     * to specify multiple values, use an index value (not a comma).
     * For example, to specify DomainName=Textbooks,Education,
     * specify DomainName(0)=Textbooks,%20Education.
     * To determine valid domain names,
     * first use this call with QueryKeywords. Domain names are returned
     * for each product (and summarized in the domain histogram, if you
     * specify DomainHistogram in IncludeSelector).<br>
     * <br>
     * A domain is a named grouping of categories whose items share
     * common product characteristics. For example, all bound books
     * have a binding or format (e.g., Hardcover), but audiobooks don't.
     * So audiobooks would have their own domain.
     * To limit your search to audiobooks, you would specify Audiobooks
     * as the domain.<br>
     * <br>
     * Only useful when QueryKeywords is specified. If you use this with
     * ProductID, AND logic is applied. In this case, if you specify an
     * ID that doesn't match the domain (as Half.com has defined it),
     * no matching product will be found. Therefore, we recommend that
     * you only use DomainName with QueryKeywords.
     * 
     *
     * @returns java.util.List<java.lang.String>
	 */
	public List<String> getDomainName() {
	    return this.domainName;
	}
	
	/**
	 * public setter
	 *
     * 
     * A domain to search in. This is like searching a section of
     * a catalog. If not specified, the product search is conducted
     * across all domains.
     * DomainName is an unbounded field. If you are using a URL, and you want
     * to specify multiple values, use an index value (not a comma).
     * For example, to specify DomainName=Textbooks,Education,
     * specify DomainName(0)=Textbooks,%20Education.
     * To determine valid domain names,
     * first use this call with QueryKeywords. Domain names are returned
     * for each product (and summarized in the domain histogram, if you
     * specify DomainHistogram in IncludeSelector).<br>
     * <br>
     * A domain is a named grouping of categories whose items share
     * common product characteristics. For example, all bound books
     * have a binding or format (e.g., Hardcover), but audiobooks don't.
     * So audiobooks would have their own domain.
     * To limit your search to audiobooks, you would specify Audiobooks
     * as the domain.<br>
     * <br>
     * Only useful when QueryKeywords is specified. If you use this with
     * ProductID, AND logic is applied. In this case, if you specify an
     * ID that doesn't match the domain (as Half.com has defined it),
     * no matching product will be found. Therefore, we recommend that
     * you only use DomainName with QueryKeywords.
     * 
     *
     * @param java.util.List<java.lang.String>
	 */
	public void setDomainName(List<String> domainName) {
	    this.domainName = domainName;
	}
	/**
     * public getter
     *
     * 
     * Use this to retrieve product details for one specific product.
     * Specify the ID as a string, and use the type attribute to
     * indicate the nature of the ID you are specifying.
     * <br>
     * <br>
     * In general, you can request up to 10 IDs of the same type by
     * separating them with commas, as in the following: 014633155310,014633145496.
     * However, if you specify a ProductID type of Reference (which specifies
     * a global reference ID for an eBay catalog product), only one ID in
     * ProductID can be used.
     * <br>
     * <br>
     * The request requires either QueryKeywords or
     * ProductID, but these fields cannot be used together.
     * <br>
     * ItemCount is only returned when ProductID is used in the request
     * and the IncludeSelector is set to Items or Details.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.ProductIDType
	 */
	public ProductIDType getProductID() {
	    return this.productID;
	}
	
	/**
	 * public setter
	 *
     * 
     * Use this to retrieve product details for one specific product.
     * Specify the ID as a string, and use the type attribute to
     * indicate the nature of the ID you are specifying.
     * <br>
     * <br>
     * In general, you can request up to 10 IDs of the same type by
     * separating them with commas, as in the following: 014633155310,014633145496.
     * However, if you specify a ProductID type of Reference (which specifies
     * a global reference ID for an eBay catalog product), only one ID in
     * ProductID can be used.
     * <br>
     * <br>
     * The request requires either QueryKeywords or
     * ProductID, but these fields cannot be used together.
     * <br>
     * ItemCount is only returned when ProductID is used in the request
     * and the IncludeSelector is set to Items or Details.
     * 
     *
     * @param ebay.apis.eblbasecomponents.ProductIDType
	 */
	public void setProductID(ProductIDType productID) {
	    this.productID = productID;
	}
	/**
     * public getter
     *
     * 
     * One or more keywords to search for. When you use a keyword search,
     * Half.com searches the product catalogs  for matching words in the
     * product title, description, and/or Item Specifics, and it returns
     * a list of matching products, with no items. To retrieve
     * items, use ProductID instead. (If you don't already have a
     * product ID, you can get product IDs from the
     * response after conducting a keyword search.)<br>
     * <br>
     * If specified, you must pass in at least 3 alphanumeric characters.<br>
     * <br>
     * The words "and" and "or" are treated like any other word.
     * Only use "and", "or", or "the" if you are searching for products
     * containing these words.
     * To use AND or OR logic, use Half.com's standard search string
     * modifiers. Wildcards (+, -, or *) are also supported.
     * Be careful when using spaces before or after modifiers and
     * wildcards.<br>
     * <br>
     * Some keyword queries can result in response times of 30 seconds or
     * longer. If more than 2000 matches are found, the call fails with
     * an error. If this kind of error occurs, refine the search by
     * passing in more keywords and/or by using DomainName to restrict
     * the search to certain domains (such as DVDs).
     * If you are searching for a particular book, DVD, CD, or video game
     * and you already know its ISBN or EAN (for a book) or UPC,
     * consider using ProductID instead to retrieve more
     * precise results. <br>
     * <br>
     * The request requires either QueryKeywords or
     * ProductID, but these fields cannot be used together.
     * <br>
     * When QueryKeywords is used in the request, ItemCount is not returned.
     * 
     *
     * @returns java.lang.String
	 */
	public String getQueryKeywords() {
	    return this.queryKeywords;
	}
	
	/**
	 * public setter
	 *
     * 
     * One or more keywords to search for. When you use a keyword search,
     * Half.com searches the product catalogs  for matching words in the
     * product title, description, and/or Item Specifics, and it returns
     * a list of matching products, with no items. To retrieve
     * items, use ProductID instead. (If you don't already have a
     * product ID, you can get product IDs from the
     * response after conducting a keyword search.)<br>
     * <br>
     * If specified, you must pass in at least 3 alphanumeric characters.<br>
     * <br>
     * The words "and" and "or" are treated like any other word.
     * Only use "and", "or", or "the" if you are searching for products
     * containing these words.
     * To use AND or OR logic, use Half.com's standard search string
     * modifiers. Wildcards (+, -, or *) are also supported.
     * Be careful when using spaces before or after modifiers and
     * wildcards.<br>
     * <br>
     * Some keyword queries can result in response times of 30 seconds or
     * longer. If more than 2000 matches are found, the call fails with
     * an error. If this kind of error occurs, refine the search by
     * passing in more keywords and/or by using DomainName to restrict
     * the search to certain domains (such as DVDs).
     * If you are searching for a particular book, DVD, CD, or video game
     * and you already know its ISBN or EAN (for a book) or UPC,
     * consider using ProductID instead to retrieve more
     * precise results. <br>
     * <br>
     * The request requires either QueryKeywords or
     * ProductID, but these fields cannot be used together.
     * <br>
     * When QueryKeywords is used in the request, ItemCount is not returned.
     * 
     *
     * @param java.lang.String
	 */
	public void setQueryKeywords(String queryKeywords) {
	    this.queryKeywords = queryKeywords;
	}
	/**
     * public getter
     *
     * 
     * The ID of a specific seller.
     * Specify this value in combination with ProductID
     * if you want search results to be filtered so that the items returned
     * are only items in a specific product, sold by a specific seller.
     * To specify SellerID, use SellerID and ProductID together.
     * 
     *
     * @returns java.lang.String
	 */
	public String getSellerID() {
	    return this.sellerID;
	}
	
	/**
	 * public setter
	 *
     * 
     * The ID of a specific seller.
     * Specify this value in combination with ProductID
     * if you want search results to be filtered so that the items returned
     * are only items in a specific product, sold by a specific seller.
     * To specify SellerID, use SellerID and ProductID together.
     * 
     *
     * @param java.lang.String
	 */
	public void setSellerID(String sellerID) {
	    this.sellerID = sellerID;
	}
	/**
     * public getter
     *
     * 
     * Sorts the list of products returned. This is mostly only useful
     * with QueryKeywords. (When you use ProductID, Half.com usually only returns one product.)
     * 
     *
     * @returns ebay.apis.eblbasecomponents.ProductSortCodeType
	 */
	public ProductSortCodeType getProductSort() {
	    return this.productSort;
	}
	
	/**
	 * public setter
	 *
     * 
     * Sorts the list of products returned. This is mostly only useful
     * with QueryKeywords. (When you use ProductID, Half.com usually only returns one product.)
     * 
     *
     * @param ebay.apis.eblbasecomponents.ProductSortCodeType
	 */
	public void setProductSort(ProductSortCodeType productSort) {
	    this.productSort = productSort;
	}
	/**
     * public getter
     *
     * 
     * Sorts the list of products returned.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.SortOrderCodeType
	 */
	public SortOrderCodeType getSortOrder() {
	    return this.sortOrder;
	}
	
	/**
	 * public setter
	 *
     * 
     * Sorts the list of products returned.
     * 
     *
     * @param ebay.apis.eblbasecomponents.SortOrderCodeType
	 */
	public void setSortOrder(SortOrderCodeType sortOrder) {
	    this.sortOrder = sortOrder;
	}
	/**
     * public getter
     *
     * 
     * Specifies the maximum number of products to return per page
     * in a single call. This is mostly only useful
     * with QueryKeywords. (When you use ProductID, Half.com usually only
     * returns one product, and up to 30 items for that product.)
     * 
     *
     * @returns java.lang.Integer
	 */
	public Integer getMaxEntries() {
	    return this.maxEntries;
	}
	
	/**
	 * public setter
	 *
     * 
     * Specifies the maximum number of products to return per page
     * in a single call. This is mostly only useful
     * with QueryKeywords. (When you use ProductID, Half.com usually only
     * returns one product, and up to 30 items for that product.)
     * 
     *
     * @param java.lang.Integer
	 */
	public void setMaxEntries(Integer maxEntries) {
	    this.maxEntries = maxEntries;
	}
	/**
     * public getter
     *
     * 
     * Specifies which page of data to return in the current call.
     * Specify a positive value equal to or lower than the number of
     * pages available (which you determine by examining the results of
     * your initial request).
     * Use this only when specifying QueryKeywords.
     * 
     *
     * @returns java.lang.Integer
	 */
	public Integer getPageNumber() {
	    return this.pageNumber;
	}
	
	/**
	 * public setter
	 *
     * 
     * Specifies which page of data to return in the current call.
     * Specify a positive value equal to or lower than the number of
     * pages available (which you determine by examining the results of
     * your initial request).
     * Use this only when specifying QueryKeywords.
     * 
     *
     * @param java.lang.Integer
	 */
	public void setPageNumber(Integer pageNumber) {
	    this.pageNumber = pageNumber;
	}

}