// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import com.leansoft.nano.annotation.*;

/**
 * 
 * Response to GetSingleItem request.
 * 
 */
@RootElement(name = "GetSingleItemResponse", namespace = "urn:ebay:apis:eBLBaseComponents")
public class GetSingleItemResponseType extends AbstractResponseType  {

	@Element(name = "Item")
	private SimpleItemType item;
    
    
	/**
     * public getter
     *
     * 
     * Contains details about the listing whose ID was specified in
     * the request.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.SimpleItemType
	 */
	public SimpleItemType getItem() {
	    return this.item;
	}
	
	/**
	 * public setter
	 *
     * 
     * Contains details about the listing whose ID was specified in
     * the request.
     * 
     *
     * @param ebay.apis.eblbasecomponents.SimpleItemType
	 */
	public void setItem(SimpleItemType item) {
	    this.item = item;
	}

}