// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Defines from one to five items and lists them on a specified eBay site.
 * 
 */
@RootElement(name = "AddItemsRequest", namespace = "urn:ebay:apis:eBLBaseComponents")
public class AddItemsRequestType extends AbstractRequestType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "AddItemRequestContainer")
	private List<AddItemRequestContainerType> addItemRequestContainer;
	
    
	/**
     * public getter
     *
     * 
     * Defines a single item to be listed on eBay. This container is similar
     * to an AddItem request. Up to five (5) containers can  be included
     * per a given AddItems request.
     * 
     *
     * @returns java.util.List<ebay.apis.eblbasecomponents.AddItemRequestContainerType>
	 */
	public List<AddItemRequestContainerType> getAddItemRequestContainer() {
	    return this.addItemRequestContainer;
	}
	
	/**
	 * public setter
	 *
     * 
     * Defines a single item to be listed on eBay. This container is similar
     * to an AddItem request. Up to five (5) containers can  be included
     * per a given AddItems request.
     * 
     *
     * @param java.util.List<ebay.apis.eblbasecomponents.AddItemRequestContainerType>
	 */
	public void setAddItemRequestContainer(List<AddItemRequestContainerType> addItemRequestContainer) {
	    this.addItemRequestContainer = addItemRequestContainer;
	}

}