// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

public class BasicAmountType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Value
	private String value;
	
	@Attribute  
	private CurrencyCodeType currencyID;
	
    
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getValue() {
	    return this.value;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setValue(String value) {
	    this.value = value;
	}
	/**
	 * public getter
	 *
     * @returns ebay.apis.eblbasecomponents.CurrencyCodeType
	 */
	public CurrencyCodeType getCurrencyID() {
	    return this.currencyID;
	}
	
	/**
	 * public setter
	 *
     * @param ebay.apis.eblbasecomponents.CurrencyCodeType
	 */
	public void setCurrencyID(CurrencyCodeType currencyID) {
	    this.currencyID = currencyID;
	}

}