// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.Date;

/**
 * 
 * The information of nonprofit charity organization affiliation.
 * 
 */
public class CharityAffiliationDetailType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "CharityID")
	private String charityID;
	
	@Element(name = "AffiliationType")
	private CharityAffiliationTypeCodeType affiliationType;
	
	@Element(name = "LastUsedTime")
	private Date lastUsedTime;
	
    
	/**
     * public getter
     *
     * 
     * The affiliation ID for nonprofit charity organizations
     * registered with the dedicated eBay Giving Works provider.
     * 
     *
     * @returns java.lang.String
	 */
	public String getCharityID() {
	    return this.charityID;
	}
	
	/**
	 * public setter
	 *
     * 
     * The affiliation ID for nonprofit charity organizations
     * registered with the dedicated eBay Giving Works provider.
     * 
     *
     * @param java.lang.String
	 */
	public void setCharityID(String charityID) {
	    this.charityID = charityID;
	}
	/**
     * public getter
     *
     * 
     * Indicates the affiliation status of the nonprofit charity
     * organization registered with the eBay Giving Works provider.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.CharityAffiliationTypeCodeType
	 */
	public CharityAffiliationTypeCodeType getAffiliationType() {
	    return this.affiliationType;
	}
	
	/**
	 * public setter
	 *
     * 
     * Indicates the affiliation status of the nonprofit charity
     * organization registered with the eBay Giving Works provider.
     * 
     *
     * @param ebay.apis.eblbasecomponents.CharityAffiliationTypeCodeType
	 */
	public void setAffiliationType(CharityAffiliationTypeCodeType affiliationType) {
	    this.affiliationType = affiliationType;
	}
	/**
     * public getter
     *
     * 
     * Indicates the affiliation last used date of the nonprofit charity
     * organization registered with the eBay Giving Works provider.
     * 
     *
     * @returns java.util.Date
	 */
	public Date getLastUsedTime() {
	    return this.lastUsedTime;
	}
	
	/**
	 * public setter
	 *
     * 
     * Indicates the affiliation last used date of the nonprofit charity
     * organization registered with the eBay Giving Works provider.
     * 
     *
     * @param java.util.Date
	 */
	public void setLastUsedTime(Date lastUsedTime) {
	    this.lastUsedTime = lastUsedTime;
	}

}