// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Defines the affiliation status for a nonprofit charity
 * organization registered with the eBay Giving Works provider.
 * 
 */
public class CharityIDType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Value
	private String value;
	
	@Attribute  
	private CharityAffiliationTypeCodeType type;
	
    
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getValue() {
	    return this.value;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setValue(String value) {
	    this.value = value;
	}
	/**
	 * public getter
	 *
     * @returns ebay.apis.eblbasecomponents.CharityAffiliationTypeCodeType
	 */
	public CharityAffiliationTypeCodeType getType() {
	    return this.type;
	}
	
	/**
	 * public setter
	 *
     * @param ebay.apis.eblbasecomponents.CharityAffiliationTypeCodeType
	 */
	public void setType(CharityAffiliationTypeCodeType type) {
	    this.type = type;
	}

}