// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Contains the set of automation rules associated with the specified template.
 * 
 */
@RootElement(name = "DeleteSellingManagerTemplateAutomationRuleResponse", namespace = "urn:ebay:apis:eBLBaseComponents")
public class DeleteSellingManagerTemplateAutomationRuleResponseType extends AbstractResponseType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "AutomatedListingRule")
	private SellingManagerAutoListType automatedListingRule;
	
	@Element(name = "AutomatedRelistingRule")
	private SellingManagerAutoRelistType automatedRelistingRule;
	
	@Element(name = "AutomatedSecondChanceOfferRule")
	private SellingManagerAutoSecondChanceOfferType automatedSecondChanceOfferRule;
	
	@Element(name = "Fees")
	private FeesType fees;
	
    
	/**
     * public getter
     *
     * 
     * Contains the remaining automated listing rules associated with this template.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.SellingManagerAutoListType
	 */
	public SellingManagerAutoListType getAutomatedListingRule() {
	    return this.automatedListingRule;
	}
	
	/**
	 * public setter
	 *
     * 
     * Contains the remaining automated listing rules associated with this template.
     * 
     *
     * @param ebay.apis.eblbasecomponents.SellingManagerAutoListType
	 */
	public void setAutomatedListingRule(SellingManagerAutoListType automatedListingRule) {
	    this.automatedListingRule = automatedListingRule;
	}
	/**
     * public getter
     *
     * 
     * Contains the remaining automated relisting rules associated with this template.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.SellingManagerAutoRelistType
	 */
	public SellingManagerAutoRelistType getAutomatedRelistingRule() {
	    return this.automatedRelistingRule;
	}
	
	/**
	 * public setter
	 *
     * 
     * Contains the remaining automated relisting rules associated with this template.
     * 
     *
     * @param ebay.apis.eblbasecomponents.SellingManagerAutoRelistType
	 */
	public void setAutomatedRelistingRule(SellingManagerAutoRelistType automatedRelistingRule) {
	    this.automatedRelistingRule = automatedRelistingRule;
	}
	/**
     * public getter
     *
     * 
     * Contains the remaining automated second chance offer rule associated with this template.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.SellingManagerAutoSecondChanceOfferType
	 */
	public SellingManagerAutoSecondChanceOfferType getAutomatedSecondChanceOfferRule() {
	    return this.automatedSecondChanceOfferRule;
	}
	
	/**
	 * public setter
	 *
     * 
     * Contains the remaining automated second chance offer rule associated with this template.
     * 
     *
     * @param ebay.apis.eblbasecomponents.SellingManagerAutoSecondChanceOfferType
	 */
	public void setAutomatedSecondChanceOfferRule(SellingManagerAutoSecondChanceOfferType automatedSecondChanceOfferRule) {
	    this.automatedSecondChanceOfferRule = automatedSecondChanceOfferRule;
	}
	/**
     * public getter
     *
     * 
     * Contains fees that may be incurred when items are listed using the 
     * automation rules (e.g., a scheduled listing fee). Use of an automation rule 
     * does not in itself have a fee, but use can result in a fee.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.FeesType
	 */
	public FeesType getFees() {
	    return this.fees;
	}
	
	/**
	 * public setter
	 *
     * 
     * Contains fees that may be incurred when items are listed using the 
     * automation rules (e.g., a scheduled listing fee). Use of an automation rule 
     * does not in itself have a fee, but use can result in a fee.
     * 
     *
     * @param ebay.apis.eblbasecomponents.FeesType
	 */
	public void setFees(FeesType fees) {
	    this.fees = fees;
	}

}