// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Indicates whether the category supports using the telephone as a 
 * contact method.
 * Added for EbayMotors Pro users.
 * 
 */
public class EBayMotorsProContactByPhoneEnabledDefinitionType implements Serializable {

    private static final long serialVersionUID = -1L;

    

}