// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Contains the seller's preferences for the email sent to the buyer after the creation of the order line item.
 * 
 */
public class EndOfAuctionEmailPreferencesType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "TemplateText")
	private String templateText;
	
	@Element(name = "LogoURL")
	private String logoURL;
	
	@Element(name = "LogoType")
	private EndOfAuctionLogoTypeCodeType logoType;
	
	@Element(name = "EmailCustomized")
	private Boolean emailCustomized;
	
	@Element(name = "TextCustomized")
	private Boolean textCustomized;
	
	@Element(name = "LogoCustomized")
	private Boolean logoCustomized;
	
	@Element(name = "CopyEmail")
	private Boolean copyEmail;
	
    
	/**
     * public getter
     *
     * 
     * The text of the custom message for the email.
     * 
     *
     * @returns java.lang.String
	 */
	public String getTemplateText() {
	    return this.templateText;
	}
	
	/**
	 * public setter
	 *
     * 
     * The text of the custom message for the email.
     * 
     *
     * @param java.lang.String
	 */
	public void setTemplateText(String templateText) {
	    this.templateText = templateText;
	}
	/**
     * public getter
     *
     * 
     * The URL of the logo to include in the customized email.
     * 
     *
     * @returns java.lang.String
	 */
	public String getLogoURL() {
	    return this.logoURL;
	}
	
	/**
	 * public setter
	 *
     * 
     * The URL of the logo to include in the customized email.
     * 
     *
     * @param java.lang.String
	 */
	public void setLogoURL(String logoURL) {
	    this.logoURL = logoURL;
	}
	/**
     * public getter
     *
     * 
     * The type of logo to include in the customized email.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.EndOfAuctionLogoTypeCodeType
	 */
	public EndOfAuctionLogoTypeCodeType getLogoType() {
	    return this.logoType;
	}
	
	/**
	 * public setter
	 *
     * 
     * The type of logo to include in the customized email.
     * 
     *
     * @param ebay.apis.eblbasecomponents.EndOfAuctionLogoTypeCodeType
	 */
	public void setLogoType(EndOfAuctionLogoTypeCodeType logoType) {
	    this.logoType = logoType;
	}
	/**
     * public getter
     *
     * 
     * Indicates whether or not the seller wishes to send a customized email to winning buyers.
     * 
     *
     * @returns java.lang.Boolean
	 */
	public Boolean getEmailCustomized() {
	    return this.emailCustomized;
	}
	
	/**
	 * public setter
	 *
     * 
     * Indicates whether or not the seller wishes to send a customized email to winning buyers.
     * 
     *
     * @param java.lang.Boolean
	 */
	public void setEmailCustomized(Boolean emailCustomized) {
	    this.emailCustomized = emailCustomized;
	}
	/**
     * public getter
     *
     * 
     * Indicates whether or not the text of the customized message will be customized.
     * 
     *
     * @returns java.lang.Boolean
	 */
	public Boolean getTextCustomized() {
	    return this.textCustomized;
	}
	
	/**
	 * public setter
	 *
     * 
     * Indicates whether or not the text of the customized message will be customized.
     * 
     *
     * @param java.lang.Boolean
	 */
	public void setTextCustomized(Boolean textCustomized) {
	    this.textCustomized = textCustomized;
	}
	/**
     * public getter
     *
     * 
     * Indicates whether or not the seller wishes to include a logo in the customized email.
     * 
     *
     * @returns java.lang.Boolean
	 */
	public Boolean getLogoCustomized() {
	    return this.logoCustomized;
	}
	
	/**
	 * public setter
	 *
     * 
     * Indicates whether or not the seller wishes to include a logo in the customized email.
     * 
     *
     * @param java.lang.Boolean
	 */
	public void setLogoCustomized(Boolean logoCustomized) {
	    this.logoCustomized = logoCustomized;
	}
	/**
     * public getter
     *
     * 
     * Indicates whether or not the seller wishes to receive a copy of the customized
     * email sent to the winning buyer.
     * 
     *
     * @returns java.lang.Boolean
	 */
	public Boolean getCopyEmail() {
	    return this.copyEmail;
	}
	
	/**
	 * public setter
	 *
     * 
     * Indicates whether or not the seller wishes to receive a copy of the customized
     * email sent to the winning buyer.
     * 
     *
     * @param java.lang.Boolean
	 */
	public void setCopyEmail(Boolean copyEmail) {
	    this.copyEmail = copyEmail;
	}

}