// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Response to a GetBidderList call, which retrieves all items the user is currently bidding on, or
 * has won or purchased.
 * 
 * 
 * 
 * Response to GetBidderListRequest.
 * 
 */
@RootElement(name = "GetBidderListResponse", namespace = "urn:ebay:apis:eBLBaseComponents")
public class GetBidderListResponseType extends AbstractResponseType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "Bidder")
	private UserType bidder;
	
	@Element(name = "BidItemArray")
	private ItemArrayType bidItemArray;
	
    
	/**
     * public getter
     *
     * 
     * Data for one eBay bidder.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.UserType
	 */
	public UserType getBidder() {
	    return this.bidder;
	}
	
	/**
	 * public setter
	 *
     * 
     * Data for one eBay bidder.
     * 
     *
     * @param ebay.apis.eblbasecomponents.UserType
	 */
	public void setBidder(UserType bidder) {
	    this.bidder = bidder;
	}
	/**
     * public getter
     *
     * 
     * Array of items the bidder has bid on, has won or has lost.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.ItemArrayType
	 */
	public ItemArrayType getBidItemArray() {
	    return this.bidItemArray;
	}
	
	/**
	 * public setter
	 *
     * 
     * Array of items the bidder has bid on, has won or has lost.
     * 
     *
     * @param ebay.apis.eblbasecomponents.ItemArrayType
	 */
	public void setBidItemArray(ItemArrayType bidItemArray) {
	    this.bidItemArray = bidItemArray;
	}

}