// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;
import java.util.Date;

/**
 * 
 * Contains a list of the products created by the seller. The list of products is returned as a set
 * of tags, in which are returned zero, one, or multiple SellingManagerProductType objects. Each
 * SellingManagerProductType object contains the information about for one Selling Manager product
 * and any Selling Manager templates the product contains.
 * 
 */
@RootElement(name = "GetSellingManagerInventoryResponse", namespace = "urn:ebay:apis:eBLBaseComponents")
public class GetSellingManagerInventoryResponseType extends AbstractResponseType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "InventoryCountLastCalculatedDate")
	private Date inventoryCountLastCalculatedDate;
	
	@Element(name = "SellingManagerProduct")
	private List<SellingManagerProductType> sellingManagerProduct;
	
	@Element(name = "PaginationResult")
	private PaginationResultType paginationResult;
	
    
	/**
     * public getter
     *
     * 
     * Returns the date the inventory counts were last calculated.
     * 
     *
     * @returns java.util.Date
	 */
	public Date getInventoryCountLastCalculatedDate() {
	    return this.inventoryCountLastCalculatedDate;
	}
	
	/**
	 * public setter
	 *
     * 
     * Returns the date the inventory counts were last calculated.
     * 
     *
     * @param java.util.Date
	 */
	public void setInventoryCountLastCalculatedDate(Date inventoryCountLastCalculatedDate) {
	    this.inventoryCountLastCalculatedDate = inventoryCountLastCalculatedDate;
	}
	/**
     * public getter
     *
     * 
     * Container for information about the requested products and templates.
     * 
     *
     * @returns java.util.List<ebay.apis.eblbasecomponents.SellingManagerProductType>
	 */
	public List<SellingManagerProductType> getSellingManagerProduct() {
	    return this.sellingManagerProduct;
	}
	
	/**
	 * public setter
	 *
     * 
     * Container for information about the requested products and templates.
     * 
     *
     * @param java.util.List<ebay.apis.eblbasecomponents.SellingManagerProductType>
	 */
	public void setSellingManagerProduct(List<SellingManagerProductType> sellingManagerProduct) {
	    this.sellingManagerProduct = sellingManagerProduct;
	}
	/**
     * public getter
     *
     * 
     * Contains the total number of pages (TotalNumberOfPages) and the total
     * number of products entries (TotalNumberOfEntries) that can be returned
     * on repeated calls with the same format and report criteria.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.PaginationResultType
	 */
	public PaginationResultType getPaginationResult() {
	    return this.paginationResult;
	}
	
	/**
	 * public setter
	 *
     * 
     * Contains the total number of pages (TotalNumberOfPages) and the total
     * number of products entries (TotalNumberOfEntries) that can be returned
     * on repeated calls with the same format and report criteria.
     * 
     *
     * @param ebay.apis.eblbasecomponents.PaginationResultType
	 */
	public void setPaginationResult(PaginationResultType paginationResult) {
	    this.paginationResult = paginationResult;
	}

}