// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.Date;

/**
 * 
 * Contains the items returned by the call. Items for which a seller event has
 * occurred (and that meet any filters specified as input) are returned in an
 * ItemArrayType object, within which are zero, one, or multiple ItemType objects.
 * Each ItemType object contains the detail data for one item listing.
 * 
 */
@RootElement(name = "GetSellerEventsResponse", namespace = "urn:ebay:apis:eBLBaseComponents")
public class GetSellerEventsResponseType extends AbstractResponseType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "TimeTo")
	private Date timeTo;
	
	@Element(name = "ItemArray")
	private ItemArrayType itemArray;
	
    
	/**
     * public getter
     *
     * 
     * Indicates the latest (most recent) date for any date-based filtering specified as
     * input. Specifically, this field contains the value you specified in the StartTimeTo, EndTimeTo, or ModTimeTo filter, if you used a time filter in the request. If no time filter was specified, TimeTo returns the current time.
     * 
     *
     * @returns java.util.Date
	 */
	public Date getTimeTo() {
	    return this.timeTo;
	}
	
	/**
	 * public setter
	 *
     * 
     * Indicates the latest (most recent) date for any date-based filtering specified as
     * input. Specifically, this field contains the value you specified in the StartTimeTo, EndTimeTo, or ModTimeTo filter, if you used a time filter in the request. If no time filter was specified, TimeTo returns the current time.
     * 
     *
     * @param java.util.Date
	 */
	public void setTimeTo(Date timeTo) {
	    this.timeTo = timeTo;
	}
	/**
     * public getter
     *
     * 
     * Collection of items whose last modified time matches
     * the filters specified in the request. 
     * Returns empty if no items were modified within the 
     * time range of the request. 
     * If 1 to 2999 items are returned, then the results are 
     * complete. If 3000 or more items are returned, it usually means 
     * additional items exist within the time range you requested, 
     * but they were not all returned. To retrieve complete results,
     * use a smaller time range in the request so that fewer than 
     * 3000 are returned per response. 
     * 
     *
     * @returns ebay.apis.eblbasecomponents.ItemArrayType
	 */
	public ItemArrayType getItemArray() {
	    return this.itemArray;
	}
	
	/**
	 * public setter
	 *
     * 
     * Collection of items whose last modified time matches
     * the filters specified in the request. 
     * Returns empty if no items were modified within the 
     * time range of the request. 
     * If 1 to 2999 items are returned, then the results are 
     * complete. If 3000 or more items are returned, it usually means 
     * additional items exist within the time range you requested, 
     * but they were not all returned. To retrieve complete results,
     * use a smaller time range in the request so that fewer than 
     * 3000 are returned per response. 
     * 
     *
     * @param ebay.apis.eblbasecomponents.ItemArrayType
	 */
	public void setItemArray(ItemArrayType itemArray) {
	    this.itemArray = itemArray;
	}

}