// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Returns the status of the processing for category-structure changes specified
 * with a call to SetStoreCategories.
 * 
 */
@RootElement(name = "GetStoreCategoryUpdateStatusRequest", namespace = "urn:ebay:apis:eBLBaseComponents")
public class GetStoreCategoryUpdateStatusRequestType extends AbstractRequestType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "TaskID")
	private Long taskID;
	
    
	/**
     * public getter
     *
     * 
     * The task ID returned by the SetStoreCategories call. If the
     * SetStoreCategories call was processed asynchronously, the TaskID will be
     * a positive number. If SetStoreCategories returned a TaskID with a value of
     * 0, the change was completed at the time the call was made (and there is
     * no need to check status).
     * 
     *
     * @returns java.lang.Long
	 */
	public Long getTaskID() {
	    return this.taskID;
	}
	
	/**
	 * public setter
	 *
     * 
     * The task ID returned by the SetStoreCategories call. If the
     * SetStoreCategories call was processed asynchronously, the TaskID will be
     * a positive number. If SetStoreCategories returned a TaskID with a value of
     * 0, the change was completed at the time the call was made (and there is
     * no need to check status).
     * 
     *
     * @param java.lang.Long
	 */
	public void setTaskID(Long taskID) {
	    this.taskID = taskID;
	}

}