// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.Date;

/**
 * 
 * Response to GetTaxTableRequest.
 * 
 */
@RootElement(name = "GetTaxTableResponse", namespace = "urn:ebay:apis:eBLBaseComponents")
public class GetTaxTableResponseType extends AbstractResponseType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "LastUpdateTime")
	private Date lastUpdateTime;
	
	@Element(name = "TaxTable")
	private TaxTableType taxTable;
	
    
	/**
     * public getter
     *
     * 
     * The last time (in GMT) that the tax table was updated.
     * Only returned if the user previously created a tax table
     * and if the site has jurisdictions.
     * LastUpdateTime is useful for synchronization. If you cache the user's
     * tax table, you can use GetTaxTable to check if it has changed and
     * whether you need to update the cached tax table.
     * 
     *
     * @returns java.util.Date
	 */
	public Date getLastUpdateTime() {
	    return this.lastUpdateTime;
	}
	
	/**
	 * public setter
	 *
     * 
     * The last time (in GMT) that the tax table was updated.
     * Only returned if the user previously created a tax table
     * and if the site has jurisdictions.
     * LastUpdateTime is useful for synchronization. If you cache the user's
     * tax table, you can use GetTaxTable to check if it has changed and
     * whether you need to update the cached tax table.
     * 
     *
     * @param java.util.Date
	 */
	public void setLastUpdateTime(Date lastUpdateTime) {
	    this.lastUpdateTime = lastUpdateTime;
	}
	/**
     * public getter
     *
     * 
     * A container of tax jurisdiction information unique to
     * a user/site combination. Empty if not set for user.
     * If DetailLevel is not specified, information is only
     * returned for the jurisdictions for which the user provided tax
     * information. If DetailLevel is ReturnAll, tax information
     * is returned for all possible jurisdictions, whether
     * specified by the user or not. ShippingIncludedInTax and
     * SalesTaxPercent are returned but are empty.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.TaxTableType
	 */
	public TaxTableType getTaxTable() {
	    return this.taxTable;
	}
	
	/**
	 * public setter
	 *
     * 
     * A container of tax jurisdiction information unique to
     * a user/site combination. Empty if not set for user.
     * If DetailLevel is not specified, information is only
     * returned for the jurisdictions for which the user provided tax
     * information. If DetailLevel is ReturnAll, tax information
     * is returned for all possible jurisdictions, whether
     * specified by the user or not. ShippingIncludedInTax and
     * SalesTaxPercent are returned but are empty.
     * 
     *
     * @param ebay.apis.eblbasecomponents.TaxTableType
	 */
	public void setTaxTable(TaxTableType taxTable) {
	    this.taxTable = taxTable;
	}

}