// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * About shipping service group 3.
 * 
 */
public class Group3MaxFlatShippingCostDefinitionType implements Serializable {

    private static final long serialVersionUID = -1L;

    

}