// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Indicates the refund amount that a seller issued to a buyer for a single Half.com order line item.
 * Refunds may only be issued for a specific order line item. Sellers do not have the ability to issue a 
 * general refund (not tied to an order line item) to a buyer.
 * 
 */
@RootElement(name = "IssueRefundResponse", namespace = "urn:ebay:apis:eBLBaseComponents")
public class IssueRefundResponseType extends AbstractResponseType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "RefundFromSeller")
	private AmountType refundFromSeller;
	
	@Element(name = "TotalRefundToBuyer")
	private AmountType totalRefundToBuyer;
	
    
	/**
     * public getter
     *
     * 
     * Total amount that the seller asked Half.com to refund to 
     * a buyer for a Half.com order line item.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.AmountType
	 */
	public AmountType getRefundFromSeller() {
	    return this.refundFromSeller;
	}
	
	/**
	 * public setter
	 *
     * 
     * Total amount that the seller asked Half.com to refund to 
     * a buyer for a Half.com order line item.
     * 
     *
     * @param ebay.apis.eblbasecomponents.AmountType
	 */
	public void setRefundFromSeller(AmountType refundFromSeller) {
	    this.refundFromSeller = refundFromSeller;
	}
	/**
     * public getter
     *
     * 
     * Total amount that Half.com refunded to the buyer (which could include the refund amount 
     * from the seller plus a refund amount from Half.com).
     * 
     *
     * @returns ebay.apis.eblbasecomponents.AmountType
	 */
	public AmountType getTotalRefundToBuyer() {
	    return this.totalRefundToBuyer;
	}
	
	/**
	 * public setter
	 *
     * 
     * Total amount that Half.com refunded to the buyer (which could include the refund amount 
     * from the seller plus a refund amount from Half.com).
     * 
     *
     * @param ebay.apis.eblbasecomponents.AmountType
	 */
	public void setTotalRefundToBuyer(AmountType totalRefundToBuyer) {
	    this.totalRefundToBuyer = totalRefundToBuyer;
	}

}