// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 *  
 * Defines the LocalListingDistancesNonSubscription feature. This feature displays all the supported local 
 * listing distances for items listed by sellers who have not subscribed to either Local Market for Vehicles 
 * or Local Market for Specialty Vehicles.
 * 
 */
public class LocalListingDistancesNonSubscriptionDefinitionType implements Serializable {

    private static final long serialVersionUID = -1L;

    

}