// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 *  
 * Defines the LocalListingDistancesSpecialty feature. This feature displays the supported local listing 
 * distances for items listed by sellers subscribed to Local Market for Specialty Vehicles.
 * 
 */
public class LocalListingDistancesSpecialtyDefinitionType implements Serializable {

    private static final long serialVersionUID = -1L;

    

}