// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Defines the details about one specific trait name.
 * 
 */
public class ModifyNameType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "Name")
	private String name;
	
	@Element(name = "NewName")
	private String newName;
	
    
	/**
     * public getter
     *
     * 
     * The current name (e.g., Material) of a variation specific
     * in the active listing. If specified, NewName must also be specified.
     * 
     *
     * @returns java.lang.String
	 */
	public String getName() {
	    return this.name;
	}
	
	/**
	 * public setter
	 *
     * 
     * The current name (e.g., Material) of a variation specific
     * in the active listing. If specified, NewName must also be specified.
     * 
     *
     * @param java.lang.String
	 */
	public void setName(String name) {
	    this.name = name;
	}
	/**
     * public getter
     *
     * 
     * The new name (e.g., Fabric) of the variation specific you are 
     * modifying.<br>
     * <br>
     * If specified, Name must also be specified. <br>
     * <br>
     * Also specify the new name (and omit the original name) in 
     * VariationSpecificsSet.<br>
     * <br>
     * After this change is made, GetItem only shows the new name in VariationSpecfiics.<br>
     * <br>
     * Note that variations that were sold while they used the old name will also be changed to use the new name in eBay's system. (This may change in the future.)<br>
     * <br>
     * If you are making other changes to a variation (such as adding new 
     * values or pictures), use consistent names to avoid unexpected 
     * results. For example, specify the same new name to identify the 
     * variation specific in VariationSpecifics and Pictures, (in addition to adding the new name here in ModifyNameList).
     * 
     *
     * @returns java.lang.String
	 */
	public String getNewName() {
	    return this.newName;
	}
	
	/**
	 * public setter
	 *
     * 
     * The new name (e.g., Fabric) of the variation specific you are 
     * modifying.<br>
     * <br>
     * If specified, Name must also be specified. <br>
     * <br>
     * Also specify the new name (and omit the original name) in 
     * VariationSpecificsSet.<br>
     * <br>
     * After this change is made, GetItem only shows the new name in VariationSpecfiics.<br>
     * <br>
     * Note that variations that were sold while they used the old name will also be changed to use the new name in eBay's system. (This may change in the future.)<br>
     * <br>
     * If you are making other changes to a variation (such as adding new 
     * values or pictures), use consistent names to avoid unexpected 
     * results. For example, specify the same new name to identify the 
     * variation specific in VariationSpecifics and Pictures, (in addition to adding the new name here in ModifyNameList).
     * 
     *
     * @param java.lang.String
	 */
	public void setNewName(String newName) {
	    this.newName = newName;
	}

}