// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * This type is deprecated because <b>MyMessagesAlert*</b> are deprecated.
 * 
 * 
 */
public class MyMessagesAlertArrayType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "Alert")
	private List<MyMessagesAlertType> alert;
	
    
	/**
     * public getter
     *
     * 
     * 
     * This container will be deprecated in an upcoming release.
     * This field formerly
     * contained the data for one alert.
     * 
     *
     * @returns java.util.List<ebay.apis.eblbasecomponents.MyMessagesAlertType>
	 */
	public List<MyMessagesAlertType> getAlert() {
	    return this.alert;
	}
	
	/**
	 * public setter
	 *
     * 
     * 
     * This container will be deprecated in an upcoming release.
     * This field formerly
     * contained the data for one alert.
     * 
     *
     * @param java.util.List<ebay.apis.eblbasecomponents.MyMessagesAlertType>
	 */
	public void setAlert(List<MyMessagesAlertType> alert) {
	    this.alert = alert;
	}

}