// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Contains a list of up to 10 external message IDs.
 * 
 */
public class MyMessagesExternalMessageIDArrayType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "ExternalMessageID")
	private List<String> externalMessageID;
	
    
	/**
     * public getter
     *
     * 
     * Currently available on the US site. A message ID that uniquely identifies a message
     * for a given user. If provided at the time of message creation, this ID can be used
     * to retrieve messages, and will take precedence over the message ID. A total of 10
     * message IDs can be specified.
     * 
     *
     * @returns java.util.List<java.lang.String>
	 */
	public List<String> getExternalMessageID() {
	    return this.externalMessageID;
	}
	
	/**
	 * public setter
	 *
     * 
     * Currently available on the US site. A message ID that uniquely identifies a message
     * for a given user. If provided at the time of message creation, this ID can be used
     * to retrieve messages, and will take precedence over the message ID. A total of 10
     * message IDs can be specified.
     * 
     *
     * @param java.util.List<java.lang.String>
	 */
	public void setExternalMessageID(List<String> externalMessageID) {
	    this.externalMessageID = externalMessageID;
	}

}