// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * A list of unique identifiers for orders.
 * 
 */
public class OrderIDArrayType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "OrderID")
	private List<String> orderID;
	
    
	/**
     * public getter
     *
     * 
     * A unique identifier that identifies a single line item or multiple line
     * item (Combined Payment) order. 
     * <br><br>
     * For the GetOrders and GetOrderTransactions calls, the OrderID field can handle a
     * hyphenated OrderLineItemID value. OrderLineItemID is a unique identifier for an
     * eBay transaction and is based upon the concatenation of ItemID and TransactionID
     * with a hyphen in between these two IDs.
     * <br><br>
     * 
     *
     * @returns java.util.List<java.lang.String>
	 */
	public List<String> getOrderID() {
	    return this.orderID;
	}
	
	/**
	 * public setter
	 *
     * 
     * A unique identifier that identifies a single line item or multiple line
     * item (Combined Payment) order. 
     * <br><br>
     * For the GetOrders and GetOrderTransactions calls, the OrderID field can handle a
     * hyphenated OrderLineItemID value. OrderLineItemID is a unique identifier for an
     * eBay transaction and is based upon the concatenation of ItemID and TransactionID
     * with a hyphen in between these two IDs.
     * <br><br>
     * 
     *
     * @param java.util.List<java.lang.String>
	 */
	public void setOrderID(List<String> orderID) {
	    this.orderID = orderID;
	}

}