// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * This type is deprecated as Cross Promotions are no longer supported in the APIs.
 * 
 * 
 */
public class PromotionDetailsType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "PromotionPrice")
	private AmountType promotionPrice;
	
	@Element(name = "PromotionPriceType")
	private PromotionItemPriceTypeCodeType promotionPriceType;
	
	@Element(name = "BidCount")
	private Integer bidCount;
	
	@Element(name = "ConvertedPromotionPrice")
	private AmountType convertedPromotionPrice;
	
    
	/**
     * public getter
     *
     * 
     * 
     * The price of the cross-promoted item in the currency of the site upon which
     * the item is listed. If the item is listed on a site different
     * from the site specified in the request, then ConvertedPromotionPrice is also
     * returned. Not related to the Promotional Price Display feature.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.AmountType
	 */
	public AmountType getPromotionPrice() {
	    return this.promotionPrice;
	}
	
	/**
	 * public setter
	 *
     * 
     * 
     * The price of the cross-promoted item in the currency of the site upon which
     * the item is listed. If the item is listed on a site different
     * from the site specified in the request, then ConvertedPromotionPrice is also
     * returned. Not related to the Promotional Price Display feature.
     * 
     *
     * @param ebay.apis.eblbasecomponents.AmountType
	 */
	public void setPromotionPrice(AmountType promotionPrice) {
	    this.promotionPrice = promotionPrice;
	}
	/**
     * public getter
     *
     * 
     * 
     * The listing type for the promoted item and how the item price is used. Not
     * related to the Promotional Price Display feature.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.PromotionItemPriceTypeCodeType
	 */
	public PromotionItemPriceTypeCodeType getPromotionPriceType() {
	    return this.promotionPriceType;
	}
	
	/**
	 * public setter
	 *
     * 
     * 
     * The listing type for the promoted item and how the item price is used. Not
     * related to the Promotional Price Display feature.
     * 
     *
     * @param ebay.apis.eblbasecomponents.PromotionItemPriceTypeCodeType
	 */
	public void setPromotionPriceType(PromotionItemPriceTypeCodeType promotionPriceType) {
	    this.promotionPriceType = promotionPriceType;
	}
	/**
     * public getter
     *
     * 
     * 
     * Bid count if the item is an auction item and has bids.
     * 
     *
     * @returns java.lang.Integer
	 */
	public Integer getBidCount() {
	    return this.bidCount;
	}
	
	/**
	 * public setter
	 *
     * 
     * 
     * Bid count if the item is an auction item and has bids.
     * 
     *
     * @param java.lang.Integer
	 */
	public void setBidCount(Integer bidCount) {
	    this.bidCount = bidCount;
	}
	/**
     * public getter
     *
     * 
     * 
     * The converted price of the cross-promoted item. Emitted
     * only when the item is listed on a site other than the site specified in the
     * request. Returns the price in the currency of the site specified in the
     * request. Not related to the Promotional Price Display feature.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.AmountType
	 */
	public AmountType getConvertedPromotionPrice() {
	    return this.convertedPromotionPrice;
	}
	
	/**
	 * public setter
	 *
     * 
     * 
     * The converted price of the cross-promoted item. Emitted
     * only when the item is listed on a site other than the site specified in the
     * request. Returns the price in the currency of the site specified in the
     * request. Not related to the Promotional Price Display feature.
     * 
     *
     * @param ebay.apis.eblbasecomponents.AmountType
	 */
	public void setConvertedPromotionPrice(AmountType convertedPromotionPrice) {
	    this.convertedPromotionPrice = convertedPromotionPrice;
	}

}