// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Details of a promotional shipping discount.
 * 
 */
public class PromotionalShippingDiscountDetailsType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "DiscountName")
	private DiscountNameCodeType discountName;
	
	@Element(name = "ShippingCost")
	private AmountType shippingCost;
	
	@Element(name = "OrderAmount")
	private AmountType orderAmount;
	
	@Element(name = "ItemCount")
	private Integer itemCount;
	
    
	/**
     * public getter
     *
     * 
     * The type of promotional shipping discount that is detailed in the profile.
     * If MaximumShippingCostPerOrder, see ShippingCost.
     * If ShippingCostXForAmountY, see ShippingCost and OrderAmount.
     * If ShippingCostXForItemCountN, see ShippingCost and ItemCount.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.DiscountNameCodeType
	 */
	public DiscountNameCodeType getDiscountName() {
	    return this.discountName;
	}
	
	/**
	 * public setter
	 *
     * 
     * The type of promotional shipping discount that is detailed in the profile.
     * If MaximumShippingCostPerOrder, see ShippingCost.
     * If ShippingCostXForAmountY, see ShippingCost and OrderAmount.
     * If ShippingCostXForItemCountN, see ShippingCost and ItemCount.
     * 
     *
     * @param ebay.apis.eblbasecomponents.DiscountNameCodeType
	 */
	public void setDiscountName(DiscountNameCodeType discountName) {
	    this.discountName = discountName;
	}
	/**
     * public getter
     *
     * 
     * This is shipping cost X, when DiscountName is either ShippingCostXForAmountY or
     * ShippingCostXForItemCountN, and is the maximum cost when DiscountName is
     * MaximumShippingCostPerOrder.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.AmountType
	 */
	public AmountType getShippingCost() {
	    return this.shippingCost;
	}
	
	/**
	 * public setter
	 *
     * 
     * This is shipping cost X, when DiscountName is either ShippingCostXForAmountY or
     * ShippingCostXForItemCountN, and is the maximum cost when DiscountName is
     * MaximumShippingCostPerOrder.
     * 
     *
     * @param ebay.apis.eblbasecomponents.AmountType
	 */
	public void setShippingCost(AmountType shippingCost) {
	    this.shippingCost = shippingCost;
	}
	/**
     * public getter
     *
     * 
     * This is the cost Y of the order (not including shipping cost),
     * when DiscountName is set to ShippingCostXForAmountY.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.AmountType
	 */
	public AmountType getOrderAmount() {
	    return this.orderAmount;
	}
	
	/**
	 * public setter
	 *
     * 
     * This is the cost Y of the order (not including shipping cost),
     * when DiscountName is set to ShippingCostXForAmountY.
     * 
     *
     * @param ebay.apis.eblbasecomponents.AmountType
	 */
	public void setOrderAmount(AmountType orderAmount) {
	    this.orderAmount = orderAmount;
	}
	/**
     * public getter
     *
     * 
     * This is the number of items, when DiscountName is set to ShippingCostXForItemsY.
     * 
     *
     * @returns java.lang.Integer
	 */
	public Integer getItemCount() {
	    return this.itemCount;
	}
	
	/**
	 * public setter
	 *
     * 
     * This is the number of items, when DiscountName is set to ShippingCostXForItemsY.
     * 
     *
     * @param java.lang.Integer
	 */
	public void setItemCount(Integer itemCount) {
	    this.itemCount = itemCount;
	}

}