// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * The order line item against which the refund was issued.
 * If an order ID is present, it indicates that the refund was issued against the entire order.
 * If an item ID and transaction ID are present, that indicates that the refund was issued against that particular order line item.
 * 
 */
public class RefundLineType extends AmountType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Attribute  
	private RefundLineTypeCodeType type;
	
    
	/**
	 * public getter
	 *
     * @returns ebay.apis.eblbasecomponents.RefundLineTypeCodeType
	 */
	public RefundLineTypeCodeType getType() {
	    return this.type;
	}
	
	/**
	 * public setter
	 *
     * @param ebay.apis.eblbasecomponents.RefundLineTypeCodeType
	 */
	public void setType(RefundLineTypeCodeType type) {
	    this.type = type;
	}

}