// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Sets the read state for messages, sets the flagged state of messages,
 * and moves messages into and out of folders.
 * 
 */
@RootElement(name = "ReviseMyMessagesRequest", namespace = "urn:ebay:apis:eBLBaseComponents")
public class ReviseMyMessagesRequestType extends AbstractRequestType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "MessageIDs")
	private MyMessagesMessageIDArrayType messageIDs;
	
	@Element(name = "AlertIDs")
	private MyMessagesAlertIDArrayType alertIDs;
	
	@Element(name = "Read")
	private Boolean read;
	
	@Element(name = "Flagged")
	private Boolean flagged;
	
	@Element(name = "FolderID")
	private Long folderID;
	
    
	/**
     * public getter
     *
     * 
     * Contains a list of up to 10 MessageID values.
     * <br><br>
     * MessageIDs must be included in
     * the request. Messages in the Sent box cannot be moved,
     * marked as Read, or Flagged.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.MyMessagesMessageIDArrayType
	 */
	public MyMessagesMessageIDArrayType getMessageIDs() {
	    return this.messageIDs;
	}
	
	/**
	 * public setter
	 *
     * 
     * Contains a list of up to 10 MessageID values.
     * <br><br>
     * MessageIDs must be included in
     * the request. Messages in the Sent box cannot be moved,
     * marked as Read, or Flagged.
     * 
     *
     * @param ebay.apis.eblbasecomponents.MyMessagesMessageIDArrayType
	 */
	public void setMessageIDs(MyMessagesMessageIDArrayType messageIDs) {
	    this.messageIDs = messageIDs;
	}
	/**
     * public getter
     *
     * 
     * This field will be deprecated in an upcoming release.
     * This field formerly contained a list of up to 10 AlertID values.
     * <br><br>
     * Alerts cannot be flagged. Alerts cannot be
     * moved into a new folder until they have been resolved.
     * <br><br>
     * Resolve alerts by marking Read (if no action is
     * required), or by using ActionURL (if action is
     * required).
     * 
     *
     * @returns ebay.apis.eblbasecomponents.MyMessagesAlertIDArrayType
	 */
	public MyMessagesAlertIDArrayType getAlertIDs() {
	    return this.alertIDs;
	}
	
	/**
	 * public setter
	 *
     * 
     * This field will be deprecated in an upcoming release.
     * This field formerly contained a list of up to 10 AlertID values.
     * <br><br>
     * Alerts cannot be flagged. Alerts cannot be
     * moved into a new folder until they have been resolved.
     * <br><br>
     * Resolve alerts by marking Read (if no action is
     * required), or by using ActionURL (if action is
     * required).
     * 
     *
     * @param ebay.apis.eblbasecomponents.MyMessagesAlertIDArrayType
	 */
	public void setAlertIDs(MyMessagesAlertIDArrayType alertIDs) {
	    this.alertIDs = alertIDs;
	}
	/**
     * public getter
     *
     * 
     * Changes the read states of all
     * messages specified in a request.
     * At least one of the following
     * must be specified in the
     * request: Read, Flagged, or FolderID.
     * Messages in the Sent box cannot be moved,
     * marked as Read, or Flagged.
     * <br><br>
     * Note that messages retrieved
     * with the API are not automatically marked Read,
     * and must be marked Read with this call.
     * 
     *
     * @returns java.lang.Boolean
	 */
	public Boolean getRead() {
	    return this.read;
	}
	
	/**
	 * public setter
	 *
     * 
     * Changes the read states of all
     * messages specified in a request.
     * At least one of the following
     * must be specified in the
     * request: Read, Flagged, or FolderID.
     * Messages in the Sent box cannot be moved,
     * marked as Read, or Flagged.
     * <br><br>
     * Note that messages retrieved
     * with the API are not automatically marked Read,
     * and must be marked Read with this call.
     * 
     *
     * @param java.lang.Boolean
	 */
	public void setRead(Boolean read) {
	    this.read = read;
	}
	/**
     * public getter
     *
     * 
     * Changes the flagged states of all messages specified in
     * a request by their MessageID values. At least one of
     * Read, Flagged, or FolderID must be specified in the
     * request. Messages in the Sent box cannot be moved,
     * marked as Read, or Flagged.
     * 
     *
     * @returns java.lang.Boolean
	 */
	public Boolean getFlagged() {
	    return this.flagged;
	}
	
	/**
	 * public setter
	 *
     * 
     * Changes the flagged states of all messages specified in
     * a request by their MessageID values. At least one of
     * Read, Flagged, or FolderID must be specified in the
     * request. Messages in the Sent box cannot be moved,
     * marked as Read, or Flagged.
     * 
     *
     * @param java.lang.Boolean
	 */
	public void setFlagged(Boolean flagged) {
	    this.flagged = flagged;
	}
	/**
     * public getter
     *
     * 
     * An ID that uniquely identifies the My Messages folder to
     * move messages into. At least one of Read,
     * Flagged, or FolderID must be specified in the request.
     * <br><br>
     * Messages
     * in the Sent box cannot be moved, marked as Read, or
     * Flagged.
     * 
     *
     * @returns java.lang.Long
	 */
	public Long getFolderID() {
	    return this.folderID;
	}
	
	/**
	 * public setter
	 *
     * 
     * An ID that uniquely identifies the My Messages folder to
     * move messages into. At least one of Read,
     * Flagged, or FolderID must be specified in the request.
     * <br><br>
     * Messages
     * in the Sent box cannot be moved, marked as Read, or
     * Flagged.
     * 
     *
     * @param java.lang.Long
	 */
	public void setFolderID(Long folderID) {
	    this.folderID = folderID;
	}

}