// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Defines the <b>SetPromotionalSaleListings</b> call request. 
 * 
 */
@RootElement(name = "SetPromotionalSaleListingsRequest", namespace = "urn:ebay:apis:eBLBaseComponents")
public class SetPromotionalSaleListingsRequestType extends AbstractRequestType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "PromotionalSaleID")
	private Long promotionalSaleID;
	
	@Element(name = "Action")
	private ModifyActionCodeType action;
	
	@Element(name = "PromotionalSaleItemIDArray")
	private ItemIDArrayType promotionalSaleItemIDArray;
	
	@Element(name = "StoreCategoryID")
	private Long storeCategoryID;
	
	@Element(name = "CategoryID")
	private Long categoryID;
	
	@Element(name = "AllFixedPriceItems")
	private Boolean allFixedPriceItems;
	
	@Element(name = "AllStoreInventoryItems")
	private Boolean allStoreInventoryItems;
	
	@Element(name = "AllAuctionItems")
	private Boolean allAuctionItems;
	
    
	/**
     * public getter
     *
     * 
     * The unique identifier of the seller's promotional sale. Based on the <b>Action</b> 
     * value, listings will either be added to or removed from the promotional sale.
     * 
     *
     * @returns java.lang.Long
	 */
	public Long getPromotionalSaleID() {
	    return this.promotionalSaleID;
	}
	
	/**
	 * public setter
	 *
     * 
     * The unique identifier of the seller's promotional sale. Based on the <b>Action</b> 
     * value, listings will either be added to or removed from the promotional sale.
     * 
     *
     * @param java.lang.Long
	 */
	public void setPromotionalSaleID(Long promotionalSaleID) {
	    this.promotionalSaleID = promotionalSaleID;
	}
	/**
     * public getter
     *
     * 
     * This required field determines whether you are adding (specify 'Add') or
     * removing (specify 'Delete) one or more listings from the promotional sale
     * identified by the <b>PromotionalSaleID</b> value in the request.
     * <br><br>
     * If you specify 'Delete', you must include one or more <b>ItemID</b>
     * values under the <b>PromotionalSaleItemIDArray</b> container, and
     * you cannot use the other filter options in the request. If you specify 'Add',
     * you can add one or more listings using any of the filtering options in the
     * request. Active auction listings that have one or more bids cannot be added to
     * or removed from a promotional sale.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.ModifyActionCodeType
	 */
	public ModifyActionCodeType getAction() {
	    return this.action;
	}
	
	/**
	 * public setter
	 *
     * 
     * This required field determines whether you are adding (specify 'Add') or
     * removing (specify 'Delete) one or more listings from the promotional sale
     * identified by the <b>PromotionalSaleID</b> value in the request.
     * <br><br>
     * If you specify 'Delete', you must include one or more <b>ItemID</b>
     * values under the <b>PromotionalSaleItemIDArray</b> container, and
     * you cannot use the other filter options in the request. If you specify 'Add',
     * you can add one or more listings using any of the filtering options in the
     * request. Active auction listings that have one or more bids cannot be added to
     * or removed from a promotional sale.
     * 
     *
     * @param ebay.apis.eblbasecomponents.ModifyActionCodeType
	 */
	public void setAction(ModifyActionCodeType action) {
	    this.action = action;
	}
	/**
     * public getter
     *
     * 
     * Container consisting of one or more <b>ItemID</b> values. Based on
     * the <b>Action</b> value, the listings identified by these 
     * <b>ItemID</b> values are either added to or removed from the 
     * promotional sale.
     * <br><br>
     * This container is required if listings are being removed (<b>Action</b>='Delete') 
     * from the promotional sale.
     *   
     *
     * @returns ebay.apis.eblbasecomponents.ItemIDArrayType
	 */
	public ItemIDArrayType getPromotionalSaleItemIDArray() {
	    return this.promotionalSaleItemIDArray;
	}
	
	/**
	 * public setter
	 *
     * 
     * Container consisting of one or more <b>ItemID</b> values. Based on
     * the <b>Action</b> value, the listings identified by these 
     * <b>ItemID</b> values are either added to or removed from the 
     * promotional sale.
     * <br><br>
     * This container is required if listings are being removed (<b>Action</b>='Delete') 
     * from the promotional sale.
     *   
     *
     * @param ebay.apis.eblbasecomponents.ItemIDArrayType
	 */
	public void setPromotionalSaleItemIDArray(ItemIDArrayType promotionalSaleItemIDArray) {
	    this.promotionalSaleItemIDArray = promotionalSaleItemIDArray;
	}
	/**
     * public getter
     *
     * 
     * If a <b>StoreCategoryID</b> value is included in the call request,
     * all active items in this store category are added to the promotional sale. This
     * field cannot be used if the <b>Action</b> field is set to 'Delete'.
     * 
     *
     * @returns java.lang.Long
	 */
	public Long getStoreCategoryID() {
	    return this.storeCategoryID;
	}
	
	/**
	 * public setter
	 *
     * 
     * If a <b>StoreCategoryID</b> value is included in the call request,
     * all active items in this store category are added to the promotional sale. This
     * field cannot be used if the <b>Action</b> field is set to 'Delete'.
     * 
     *
     * @param java.lang.Long
	 */
	public void setStoreCategoryID(Long storeCategoryID) {
	    this.storeCategoryID = storeCategoryID;
	}
	/**
     * public getter
     *
     * 
     * If a <b>CategoryID</b> value is included in the call request,
     * all active items in this eBay category are added to the promotional sale. This
     * field cannot be used if the <b>Action</b> field is set to 'Delete'.
     * 
     *
     * @returns java.lang.Long
	 */
	public Long getCategoryID() {
	    return this.categoryID;
	}
	
	/**
	 * public setter
	 *
     * 
     * If a <b>CategoryID</b> value is included in the call request,
     * all active items in this eBay category are added to the promotional sale. This
     * field cannot be used if the <b>Action</b> field is set to 'Delete'.
     * 
     *
     * @param java.lang.Long
	 */
	public void setCategoryID(Long categoryID) {
	    this.categoryID = categoryID;
	}
	/**
     * public getter
     *
     * 
     * If this field is included and set to 'true' in the call request, all fixed-price
     * listings are added to the promotional sale. This field cannot be used if the
     * <b>Action</b> field is set to 'Delete'.
     * 
     *
     * @returns java.lang.Boolean
	 */
	public Boolean getAllFixedPriceItems() {
	    return this.allFixedPriceItems;
	}
	
	/**
	 * public setter
	 *
     * 
     * If this field is included and set to 'true' in the call request, all fixed-price
     * listings are added to the promotional sale. This field cannot be used if the
     * <b>Action</b> field is set to 'Delete'.
     * 
     *
     * @param java.lang.Boolean
	 */
	public void setAllFixedPriceItems(Boolean allFixedPriceItems) {
	    this.allFixedPriceItems = allFixedPriceItems;
	}
	/**
     * public getter
     *
     * 
     * If this field is included and set to 'true' in the call request, all store inventory
     * items are added to the promotional sale. This field cannot be used if the
     * <b>Action</b> field is set to 'Delete'.
     * 
     *
     * @returns java.lang.Boolean
	 */
	public Boolean getAllStoreInventoryItems() {
	    return this.allStoreInventoryItems;
	}
	
	/**
	 * public setter
	 *
     * 
     * If this field is included and set to 'true' in the call request, all store inventory
     * items are added to the promotional sale. This field cannot be used if the
     * <b>Action</b> field is set to 'Delete'.
     * 
     *
     * @param java.lang.Boolean
	 */
	public void setAllStoreInventoryItems(Boolean allStoreInventoryItems) {
	    this.allStoreInventoryItems = allStoreInventoryItems;
	}
	/**
     * public getter
     *
     * 
     * If this field is included and set to 'true' in the call request, all auction
     * listings are added to the promotional sale. This field cannot be used if the
     * <b>Action</b> field is set to 'Delete'.
     * 
     *
     * @returns java.lang.Boolean
	 */
	public Boolean getAllAuctionItems() {
	    return this.allAuctionItems;
	}
	
	/**
	 * public setter
	 *
     * 
     * If this field is included and set to 'true' in the call request, all auction
     * listings are added to the promotional sale. This field cannot be used if the
     * <b>Action</b> field is set to 'Delete'.
     * 
     *
     * @param java.lang.Boolean
	 */
	public void setAllAuctionItems(Boolean allAuctionItems) {
	    this.allAuctionItems = allAuctionItems;
	}

}