// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 *           Contains the status of a promotional sale.
 * 
 */
@RootElement(name = "SetPromotionalSaleListingsResponse", namespace = "urn:ebay:apis:eBLBaseComponents")
public class SetPromotionalSaleListingsResponseType extends AbstractResponseType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "Status")
	private PromotionalSaleStatusCodeType status;
	
    
	/**
     * public getter
     *
     * 
     * Contains the status of a promotional sale.
     * 
     *
     * @returns ebay.apis.eblbasecomponents.PromotionalSaleStatusCodeType
	 */
	public PromotionalSaleStatusCodeType getStatus() {
	    return this.status;
	}
	
	/**
	 * public setter
	 *
     * 
     * Contains the status of a promotional sale.
     * 
     *
     * @param ebay.apis.eblbasecomponents.PromotionalSaleStatusCodeType
	 */
	public void setStatus(PromotionalSaleStatusCodeType status) {
	    this.status = status;
	}

}