// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 *          This type provides information about one or more order line items in a Global Shipping Program package.
 * 
 */
public class ShipmentLineItemType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "LineItem")
	private List<LineItemType> lineItem;
	
    
	/**
     * public getter
     *
     * 
     *    Contains information about one order line item in a Global Shipping Program package. The package can contain multiple units of a given order line item, and multiple order line items.
     * 
     *
     * @returns java.util.List<ebay.apis.eblbasecomponents.LineItemType>
	 */
	public List<LineItemType> getLineItem() {
	    return this.lineItem;
	}
	
	/**
	 * public setter
	 *
     * 
     *    Contains information about one order line item in a Global Shipping Program package. The package can contain multiple units of a given order line item, and multiple order line items.
     * 
     *
     * @param java.util.List<ebay.apis.eblbasecomponents.LineItemType>
	 */
	public void setLineItem(List<LineItemType> lineItem) {
	    this.lineItem = lineItem;
	}

}